### ISSUE TITLE
The ongoing content audit

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#102]
We should check in on this later this afternoon, @tsl-lindsay, to do status updates, see if we're in peril of not hitting launch goals/generally sanity-check everything. Once we hit launch-state, we can pull out the remaining goals for a post-launch push.

**Comment by kissane** [comment]
Making a note to remember that this includes recent repos—need to check for working repo embeds, logos, etc.

**Comment by kissane** [comment]
@tsl-lindsay and I talked this through, and we're doing pretty well. https://github.com/OpenNews/opennews-source/issues/109 is the exception, so I've waved for help there.

**Comment by kissane** [comment]
@tsl-lindsay, might you have Simon Elvery's XKCD-style narrative charts images? I can't find them anywhere. :/

**Comment by kissane** [comment]
Same with Jennifer Stark's uber article: https://opennews-source-staging.herokuapp.com/articles/how-i-investigated-uber-surge-pricing-dc/

**Comment by kissane** [comment]
Same with Eva's: https://opennews-source-staging.herokuapp.com/articles/data-journalism-should-thrive-cross-border-collabo/

**Comment by tsl-lindsay** [comment]
Looking for the others, this is Tiff's - https://opennews-source-staging.herokuapp.com/articles/unlearning/

https://unsplash.com/@sylwiabartyzel?photo=L4NfLl7SJGU

**Comment by tsl-lindsay** [comment]
Okie! I have all of these. I'll restore 'em right now.

**Comment by kissane** [comment]
We're gonna have to go back to Matt for these, as Kio's stash doesn't have 'em and I didn't produce it. https://opennews-source-staging.herokuapp.com/articles/true-facts-maybe/

**Comment by kissane** [comment]
Noting here that this is mostly fixed but kind of a hairball: https://opennews-source-staging.herokuapp.com/articles/when-and-how-use-census-microdata/

**Comment by kissane** [comment]
All the GIFs in Lena's loops article have died, presumably because of their weird Javascript. Which, tbh, I can kill if that's the best thing. Just noting it here. https://opennews-source-staging.herokuapp.com/articles/power-loops/

**Comment by kissane** [comment]
Hmmmm. @tsl-lindsay, could you have produced this one, or is it before your time? https://opennews-source-staging.herokuapp.com/articles/tracking-amtrak-188/

**Comment by kissane** [comment]
And we'll have to go back to Eva for this one: https://opennews-source-staging.herokuapp.com/articles/developing-data-journalists-developing-world/

**Comment by tsl-lindsay** [comment]
I think I had _just_ started then. Let me investigate!

**Comment by tsl-lindsay** [comment]
@kissane For the Amtrak story, I have one of the graphics in their original draft doc but not the cover image (which looks like it was a screenshot.) 

I didn't produce that one: do you have any memory of what the screenshot would have been? 

I think we can safely pull a new one if no.

**Comment by kissane** [comment]
I have nooooo idea, alas, but I fully advocate faking it

**Comment by kissane** [comment]
Or just clearing the image, it's fine—no need to spend time reconstructing. (There's a checkbox for clearing cover images)

**Comment by tsl-lindsay** [comment]
I'll just add a new screenshot, v simple, thx!

**Comment by kissane** [comment]
wooo

**Comment by kissane** [comment]
I have begun murdering the troublesome images. Ruthlessly.

**Comment by kissane** [comment]
Another for you, @tsl-lindsay, if you can remember: https://opennews-source-staging.herokuapp.com/articles/story-changes-based-readers-birth-year-how-we-made/

**Comment by tsl-lindsay** [comment]
OOoo I bet I can do the cover but may need to murder the animation

**Comment by kissane** [comment]
murder it 🔪

**Comment by tsl-lindsay** [comment]
done, and miraculously I HAD THE ANIMATION so a GIF soul got more time on this planet today.

**Comment by kissane** [comment]
good fairy lindsay

**Comment by ryanpitts** [comment]
@kissane I was worried about the Lena gifs article. The javascript on the new site loads faster and cleaner than it ever did before, but it also is more complicated to add special per-article js now. When there's time, I'd like to talk to Ethan about how best to approach. Not sure what this means for Lena's story rn though.

**Comment by kissane** [comment]
OK, all the articles missing cover images in the top 250 list + recent lists either have their covers restored or have been flagged for follow-up with authors after we exhausted our local images. (The ones we're following up on are all missing more than the covers—things that were just missing a cover that we couldn't find now just have no covers, in most cases, but there aren't very many of those.)

There's a list of about 20 articles left that have covers but have broken inline images that I will fix or flag after dinner, but we are very very close to the launch goal for the articles.

After that, there are some repos and orgs to do, and a few more People photos. @tsl-lindsay, if you're working this evening for a bit, which is totally not required, may I give you some logos to hunt down? We need the orgs mentioned in the last 20 articles, I think.

**Comment by tsl-lindsay** [comment]
These last 20 are done!

**Comment by tsl-lindsay** [comment]
So @kissane - the logos are displaying in a somewhat crunched-up fashion. Feels on this?

![screen shot 2017-02-08 at 6 25 32 pm](https://cloud.githubusercontent.com/assets/5169986/22763709/0543abae-ee2c-11e6-9985-348a5983040e.png)

**Comment by tsl-lindsay** [comment]
Meantime, I'm gonna just try to make them all the width of the Vox one

**Comment by ryanpitts** [comment]
All promo slots in the new design crop to a 3:2 aspect ratio (at full browser width, they're 300x200). One way to approach this, at least, would be to upload image files with built-in whitespace around the logo that gives it that aspect ratio.

**Comment by tsl-lindsay** [comment]
Ooo, genius, thanks @ryanpitts

**Comment by kissane** [comment]
Thanks, @tsl-lindsay!

Also I have another image-finding request for you for whenever, no hurry. https://opennews-source-staging.herokuapp.com/articles/how-we-made-3d-model-pulse-nightclub/

**Comment by tsl-lindsay** [comment]
Excellent - working on that one now

**Comment by kissane** [comment]
On mooooore waah https://opennews-source-staging.herokuapp.com/articles/digital-self-defense-journalists-introduction/

**Comment by kissane** [comment]
Also https://opennews-source-staging.herokuapp.com/articles/virtual-reality-rest-us/

**Comment by kissane** [comment]
And here we have a YouTube embed that's MIA (in Safari as well as Chrome) — @ryanpitts, should I be doing something different to get those to appear for us? https://opennews-source-staging.herokuapp.com/articles/slouching-toward-sensor-journalism/

**Comment by ryanpitts** [comment]
@kissane looks like all you need to do is change the iframe src attribute to an https link rather than http. I think the browser is blocking this because we're serving https, not anything to do with site code.

**Comment by tsl-lindsay** [comment]
Those three are done @kissane - just fixing image paths. I can check for
this in more articles where the article images are MIA, unless you have
tabz open.

**Comment by kissane** [comment]
@ryanpitts Eeeeeasy ok awesome thanks!

**Comment by kissane** [comment]
@tsl-lindsay I have four million tabs open, but wait—were those images actually on the server after all? I didn't have local copies, so I passed them to you, urk, sorry. (How were the paths malformed?)

**Comment by ryanpitts** [comment]
I'm making a quick pass and updating other http youtube links

**Comment by kissane** [comment]
Any idea if you have these, @tsl-lindsay? https://opennews-source-staging.herokuapp.com/articles/better-docs/

**Comment by tsl-lindsay** [comment]
The path was pointing to a media folder and was a relative path.. if I find
another one I will copy it in. No prob!

I do have those, for Better Docs!

**Comment by kissane** [comment]
And all our featured repos now have images.

**Comment by kissane** [comment]
And we now have photos for pretttty much everyone who will be a featured Person.

**Comment by kissane** [comment]
I AM CLOSING THIS
