### ISSUE TITLE
Feature some articles

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#106]
Yep

**Comment by kissane** [comment]
Excitingly, when I try to feature a new article at https://opennews-source-staging.herokuapp.com/admin/articles/article/, I get an error on save.

**Comment by kissane** [comment]
I am able to make changes to featured-ness on the individual article pages, so I'll wait for the cache to expire and see if they took. (We lost the old homepage cache-buster button, I think?)

**Comment by ryanpitts** [comment]
@kissane Ah, the batch update isn't working?! Will take a look.

**Comment by ryanpitts** [comment]
@kissane batch saving should work on the articles admin now. The admin was doing some data cleanup on the `tags` fields, which is present when you're looking at the detail view of one article, but not when you're on the list view of multiple articles. Sorry!

**Comment by kissane** [comment]
Ah, fabulous, thank you!

**Comment by kissane** [comment]
Tested and all set.
