### ISSUE TITLE
point source.opennews.org at the Heroku app, enable SSL

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#108]
This is going to be a bit quirky. I can't actually get the SSL cert for the Heroku app until the domain is pointed there. So going to be a bit of a shuffle, with possibly some temporary awkwardness while the cert gets approved.

**Comment by kissane** [comment]
Sounds like this is maybe a late-Wednesday-night thing?

**Comment by ryanpitts** [comment]
I think so, although I also have the [current production app](opennews-source.herokuapp.com) running on a branch that has all the old templates and behaviors. I'm kind of tempted to switch over early? The only difference between this and old Source would be the auto redirect of `/en-US/` URLs.

**Comment by kissane** [comment]
Ooooh yeah, gotcha, do it do it yep.

**Comment by ryanpitts** [comment]
this is done
