### ISSUE TITLE
Behavior change for featured People

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#110]
Now that I'm seeing how it's working to have non-author contributors—who are often very difficult to get bio/photo details from—in the "featured people" pool, I am wondering if we should just bring this under manual control for the first month or so of the new site running, till we can get all our bio details solid. 

If that's too troublesome for this stage in the launch prep, can we just pull recent authors and not contributors, instead?

**Comment by ryanpitts** [comment]
We can do either one. It seems like plucking from just authors is the simplest method?

**Comment by ryanpitts** [comment]
I'll push an update that plucks people only from authors of the 30 most recent articles. If this doesn't feel OK, we can add a manual thing instead.

**Comment by kissane** [comment]
Thank you, sounds great. 20 would be easier than 30, though, while we're hustling. :D

**Comment by ryanpitts** [comment]
done
