### ISSUE TITLE
Bug: saving article errors out

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#111]
Saving edits on https://opennews-source-staging.herokuapp.com/admin/articles/article/609/change/ produces a Page Not Found error. 

Not a launch-critical thing, but a bug.

**Comment by kissane** [comment]
Hmm. Happening here, too. https://opennews-source-staging.herokuapp.com/admin/articles/article/546/change/?_changelist_filters=q%3Dhamilton

**Comment by kissane** [comment]
Aaaand here. https://opennews-source-staging.herokuapp.com/admin/articles/article/279/change/?_changelist_filters=q%3Dpourover

It's happening on every article I'm trying to add images to or otherwise fix, so we should bump up the priority on this.

**Comment by ryanpitts** [comment]
BAH. Looking at this right now.

**Comment by kissane** [comment]
Stupid evening bugs. The worst, like the mosquitos that give you malaria. And shit-bees.

**Comment by ryanpitts** [comment]
OK, back in business!

**Comment by kissane** [comment]
Whoop!
