### ISSUE TITLE
question about code_detail page

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#114]
was looking at a couple of the code pages and started wondering if the link to the actual repo was minimized more than we want. In most cases, it's at left under the summary description, as in

![screen shot 2017-02-08 at 9 17 32 am](https://cloud.githubusercontent.com/assets/56477/22748800/2077674a-ede0-11e6-9264-e8aa86951027.png)

But when we don't have "demo site" or "last pushed" data for a repo, that link floats over the to right and kind of disappears, as in

![screen shot 2017-02-08 at 9 18 14 am](https://cloud.githubusercontent.com/assets/56477/22748809/264d6e1c-ede0-11e6-9fce-8b68dafd5c72.png)

Feels like it'll be a very common use case for people to want to jump from these pages to the GitHub repo, and I found myself searching for that link even though I knew where it was supposed to be.

So a couple thoughts:

1) @beep it looks like this is following this rule:

```
    .repo-meta li:last-child {
        flex: 1;
        text-align: right;
        margin-right: 0;
    }
```
And editing to this will pull solo links back over to the left:
```
    .repo-meta li:last-child {
        flex: 1;
        text-align: right;
        margin-right: 0;
    }
    .repo-meta li:first-child {
        text-align: left;
    }
```
Any unforeseen consequences I'm missing?

2) @beep @kissane here's an and/or option along with the above, is is adding a "see the repo" link to the summary graf too ... duplicative?

![screen shot 2017-02-08 at 9 33 57 am](https://cloud.githubusercontent.com/assets/56477/22749330/c9a649a2-ede1-11e6-8ff8-6770d6b16748.png)

**Comment by kissane** [comment]
> here's an and/or option along with the above, is is adding a "see the repo" link to the summary graf too ... duplicative?

I am totally fine with this, we do similar things many other places.

**Comment by beep** [comment]
@ryanpitts hi sorry i’ve been in meetings all morning, just getting re-situated now. more soon!

**Comment by beep** [comment]
> Any unforeseen consequences I'm missing?

@ryanpitts Nope, that looks fine!

> here's an and/or option along with the above, is is adding a "see the repo" link to the summary graf too ... duplicative?

I think that looks stellar. (Perhaps “Visit the repo” for non-sighted visitors?)

**Comment by ryanpitts** [comment]
awesome, will push both these changes

**Comment by ryanpitts** [comment]
closed with https://github.com/OpenNews/opennews-source/commit/d18d81f503d14faceebc9476b3498b19de279ba2
