### ISSUE TITLE
new opennews footer language

### ISSUE THREAD

**Issue by erikao** [OpenNews/opennews-source#115]
we've got updated language for the about opennews section of the source site footer

[OpenNews](opennews.org) connects a network of developers, designers, journalists, and editors to collaborate on open technologies and processes within journalism. OpenNews believes that a community of peers working, learning, and solving problems together can create a stronger, more responsive, and ascendant journalism ecosystem. Incubated at the [Mozilla Foundation](https://www.mozilla.org/en-US/foundation/) from 2011-2016, OpenNews is now a project of [Community Partners](communitypartners.org).

**Comment by ryanpitts** [comment]
@erikao I have this in place locally. Before I push, here's a screenshot:

![screen shot 2017-02-08 at 1 00 19 pm](https://cloud.githubusercontent.com/assets/56477/22757201/ce92a024-edfe-11e6-9eaa-7ad3b15668d2.png)

I imagine a lot of that text has been carefully thought through, so if we can't change anything, that's fine. Just posting in case we can kill one word to pull that widow up and line up with the CC BY line at left.

**Comment by erikao** [comment]
hmm, maybe @sinker has feels on that. i feel like we probably could drop the first or second line (we've used variations of this all over the opennews site). i don't have strong feelings about how to shorten it. but both for the attribution and for sort of mirroring the source length, shorter sounds good to me.

**Comment by ryanpitts** [comment]
I'll note that removing "of peers" OR "and ascendant" will pull up that widow line.

**Comment by erikao** [comment]
i'd say go ahead and adjust in the way you think makes sense. i highly doubt mozilla is gonna diff the descriptions on each site.

**Comment by ryanpitts** [comment]
cool, will do. I think keeping "peers" feels right fwiw, will clip the other clause.
