### ISSUE TITLE
Can't add Source articles

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#121]
When I try to save a Source article on the prod server, I get a Heroku application error that looks like this. 

<img width="567" alt="screen shot 2017-02-09 at 8 03 39 am" src="https://cloud.githubusercontent.com/assets/1910034/22784539/69ca5f56-ee9e-11e6-8285-03911172fe20.png">

**Comment by ryanpitts** [comment]
Here's the error that's happening:

> ERROR:  null value in column "lead_image_has_border" violates not-null constraint

So the issue should go away once we push the new code to production. (The "old-templates" version that's running for the moment doesn't have that field in the admin.)

**Comment by ryanpitts** [comment]
since the intro post is up, probably safe to close this one
