### ISSUE TITLE
brief flash of unenhanced content on staging

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#123]
Per https://github.com/OpenNews/opennews-source/issues/117#issuecomment-278641903:

> @beep one thing I'm noticing is that I get a brief flash of the search box on pages when I look at https://opennews-source-staging.herokuapp.com/ on my phone and tablet. Is that just me?

Something’s slowing up `initial.js`, looks like.

**Comment by ryanpitts** [comment]
possible that it might be `listfilter-load.js`, now that I'm testing for the presence of a few elements on page? If so, I could go back to dropping vars into the `head` on those pages, and just doing the `typeof` thing again.

**Comment by beep** [comment]
@ryanpitts: Nah, I think this one’s on me! Working on a couple patches now.

**Comment by beep** [comment]
@ryanpitts Just pushed a bunch of fixes that should help with this. Specifically, there’re two fixes for this bug, which I’ve tossed in that `.hed-label` PR (#122):

1. I’ve moved `typekit.js` out of initial.js, and over to the conditionally-loaded `main.js`. (3a1ebdf282589ec69258f6a5c7b56438e28035f1) This means that typekit’s only going to run on “enhanced” browsers, but that’ll lighten our initial payload.
2. I’ve added a few CSS patches to _hide_ certain parts of the UI while the JS finishes enhancing them. (b0b4a9108ee06e51d023e42deb50b097878be5f3) This makes our JS a bit optimistic, as it’s now assuming the JS’ll run successfully to re-enable those components, but that’ll make for a smoother browsing experience.

These two fixes could probably be decoupled, if need be. But! How do they look to you?

**Comment by ryanpitts** [comment]
OK, that fix is live on staging for a look: https://opennews-source-staging.herokuapp.com/

**Comment by ryanpitts** [comment]
Looks like that fix worked great. Will wait till someone else confirms though before going to prod.

**Comment by beep** [comment]
Just browsing around a bit on my iPhone, and things seem much, much smoother.

**Comment by kissane** [comment]
Same, saaaame.

**Comment by ryanpitts** [comment]
looking good on prod

**Comment by ryanpitts** [comment]
remember that one time when @beep fixed this on the fly in like 10 minutes and we got to push it live during launch? that was awesome

**Comment by beep** [comment]
[](https://bukk.it/BREAM.gif)

(sorry i let that bug slip past me, though!)
