### ISSUE TITLE
Disqus not loading on intro post

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#124]
https://source.opennews.org/articles/hello-again/

¯\_(ツ)_/¯

**Comment by beep** [comment]
@ryanpitts Dumb question, but: does `this.page.url` have to include the protocol?

(e.g., does `'//source.opennews.org/articles/hello-again/'` have to be `https://source.opennews.org/articles/hello-again/'`?)

**Comment by ryanpitts** [comment]
it _shouldn't_, but that's exactly what I was looking at as well. The other articles might have already been in the Disqus db from the old site.

**Comment by ryanpitts** [comment]
I'm going to merge the fixes from https://github.com/OpenNews/opennews-source/issues/123, and then update that bit of the template, and push to staging

**Comment by ryanpitts** [comment]
yerrrr

![screen shot 2017-02-09 at 6 37 44 am](https://cloud.githubusercontent.com/assets/56477/22787779/511b5a2a-ee92-11e6-874a-2ede7267ef39.png)

**Comment by ryanpitts** [comment]
this was, in fact, fixed by adding specific protocol to `this.page.url`
