### ISSUE TITLE
weird bug, I think, with initial.js?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#13]
@beep I ran into a funky js error while translating things into a base Django template. At this point I only have a pretty shallow hold on what each piece of the compiled `initial.js` is doing, but I reverse-engineered something that _seems_ to fix and will do my best to explain here.

I was seeing a similar effect as at the top of [this demo page](http://sourcedev.ethanmarcotte.com/article.php), where the nav menu has the blue field, the hr doesn't nestle against the `main` element, and the search menu js isn't working.

![screen shot 2017-01-19 at 5 24 25 pm](https://cloud.githubusercontent.com/assets/56477/22132012/3382a558-de6c-11e6-90a3-20b2d3078690.png)

My console was throwing a reference error "w is not defined," pointing to the middle of the minified `initial.js`. In hopes of getting a more helpful error message, I replaced the template call to that minified file with individual calls to its [components listed in the gruntfile](https://github.com/OpenNews/opennews-source/blob/master/Gruntfile.js#L62-L71). Same error, but now pointing to:

> var doc = w.document;

at [line 33](https://github.com/OpenNews/opennews-source/blob/master/tmpl/js/utils.js#L33) of `utils.js`. Couldn't find references to a `var w` anywhere in any of the files, so was thinking typo maybe. Based on what was getting passed into the outer function (plus the clue that it was looking for something with a `document` attribute), I guessed that this might work:

> var doc = win.document;

and sure enough, the page cleaned up beautifully. I'm not sure what really is going on there, or why it doesn't throw a similar error on [the other demo page](http://sourcedev.ethanmarcotte.com/landing-code.php). So I figured I'd at least step through what I was seeing and what seems to fix the problem. Hopefully I'm not breaking something else unwittingly!

**Comment by ryanpitts** [comment]
Bah, well my fix wasn't as fixy as I thought it was. It _does_ take care of the issue described above on my local machine, but when I pushed an initial version to Heroku, I see the same problem again.

https://opennews-source-staging.herokuapp.com/code/

Console message:
```
Uncaught TypeError: Cannot read property 'createElement' of undefined
    at Object.c [as loadCSS] (initial.js:1)
```
I'm at a bit of a loss for now, not knowing exactly what that bit of js is intending to do.

**Comment by beep** [comment]
Hey Ryan, sorry you ran into that! I have a meeting this morning, but I’ll take a look as soon as I'm back online.

Related question: how involved is it to get the Django app running on my machine? Might help me better debug issues on the integrated code.

Thanks! More anon,

-- 
Ethan

**Comment by beep** [comment]
@ryanpitts Related to that, are you still seeing this error?

> I was seeing a similar effect as at the top of [this demo page](http://sourcedev.ethanmarcotte.com/article.php), where the nav menu has the blue field, the hr doesn't nestle against the main element, and the search menu js isn't working.

Right now, I’m unable to reproduce. If you’re still seeing it, mind letting me know which browser you’re using? Thanks!

**Comment by beep** [comment]
Okay, I think I figured it out—sorry about the bug, @ryanpitts. Opened a PR (#18) that should sort things out.

**Comment by ryanpitts** [comment]
AW YEAH

**Comment by ryanpitts** [comment]
AW YEAH https://opennews-source-staging.herokuapp.com/code/

**Comment by ryanpitts** [comment]
looking good, closing this one down. Will open a different issue with some editorial stuff for that page.
