### ISSUE TITLE
manual redirect trubs

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#134]
I noticed this morning that https://source.opennews.org/articles/why-mobile-data-visualization-shouldnt-hurt/ was 404ing, so I made a redirect in the CMS to move it to https://source.opennews.org/articles/mobile-data-visualization-shouldnt-hurt/ where it lives now, but after two hours, it's still not redirecting. Maybe it's a cache thing? Not a high priority, but peculiar.

**Comment by ryanpitts** [comment]
Fixed! (Redirects in the admin need to not include the domain, just the path afterward)

**Comment by kissane** [comment]
WAH WAH thx
