### ISSUE TITLE
Bolded text isn't showing up bolded

### ISSUE THREAD

**Issue by tsl-lindsay** [OpenNews/opennews-source#136]
I'm having some trouble with the `<strong>` tag -- things aren't looking, well, stronger than the other text. I first noticed this in Martin's piece, where I ended up changing those bolded sentences to `<h4>`s

https://source.opennews.org/articles/worthy-of-data-breach/

**Comment by tsl-lindsay** [comment]
Or you know what? Maybe it is bolded but is just pretty subtle, and my NICAR-weary eyes just missed it.

**Comment by kissane** [comment]
The bold text in Robin's piece is showing up so it might have been the hotel wifi not loading all the fonts

**Comment by ryanpitts** [comment]
Definitely could be it, or just monitor contrast? Wrapped "easy to imagine" in `strong` tags to test, and it seems to be ok here:

![screen shot 2017-03-09 at 12 43 24 pm](https://cloud.githubusercontent.com/assets/56477/23769992/20fa013a-04c6-11e7-93a4-35b2998acc3d.png)

**Comment by kissane** [comment]
Yeah, it's all looking good from here on my tests as well, so I think we're ok

**Comment by ryanpitts** [comment]
going ahead and closing this one, will still check in on the stuff identified in #139
