### ISSUE TITLE
Guides bug, I think

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#138]
When I try to preview this guide https://source.opennews.org/admin/guides/guide/7/change/

I get a 404 at https://source.opennews.org/guides/source-guide-census-reporting/

…and this is true whether or not the View on Site box is checked. Other guides are working as expected. Hrrrrrm.

**Comment by ryanpitts** [comment]
hmm, yep, I just got a 500 alert on that URL as well. Will investigate.

**Comment by kissane** [comment]
500, indeed!

**Comment by ryanpitts** [comment]
oh whoops, this is happening because I wasn't testing for the existence of `guide.image` in the Facebook/Twitter OG tags in the head, and the thumbnailer doesn't fail silently in this case.

**Comment by kissane** [comment]
ahhhhhh that makes sense

**Comment by ryanpitts** [comment]
pushing a fix to staging

**Comment by ryanpitts** [comment]
ok, we're all good in production! https://source.opennews.org/guides/source-guide-census-reporting/

closing this ticket in https://github.com/OpenNews/opennews-source/commit/1a4414f941b88277fb30ba9a3c6ba3e735372c78

**Comment by kissane** [comment]
YAY THANKS
