### ISSUE TITLE
Editorial: destination for "see all"/"see more" links on Code landing page

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#14]
@kissane the [wireframe for the Code landing page](https://wireframe.cc/Ue7dtR) shows a "See More" link under the Featured Repos section, and a "See All" link under the Newest Repos list. Now that I'm implementing this template, I realize that I'm not clear on what those are pointing to.

I _think_ this landing page is intended to serve as the full list of Code items in our database, via the "Explore" list grouped by tag at the bottom of the page. That's what the page does right now, at least, and I'm not seeing any other new Code list [wireframes](https://github.com/OpenNews/opennews-source/issues/2).

I'm leaning toward hiding those links for now. Does that sound right?

**Comment by kissane** [comment]
Hide 'em—I no longer remember what we'd imagined they might do, and the behavior you describe here is the one I'd been assuming for awhile now.

**Comment by ryanpitts** [comment]
👍 

Followup question -- are we anticipating the tags to link to a filtered list? Or to just be visual context?

Currently a tag links to a filtered version of the code list page, which has the exact same alphabetized display but a pared-down list of code items. The way the information is organized on the new page, though, doesn't seem like we can take this same approach. A few possibilities:

* We leave the tags as links, and provide an alternate "basic list display" of matching code items when someone clicks on one. (Removing the "Featured" block and replacing the "Explore" block?)
* We just make tags not be links.
* We don't display tags, but rather just a single category "grouping" like exists in the "Explore" section of the page: https://opennews-source-staging.herokuapp.com/code/. (This "grouping" is a new field in the db, alongside the current tagging fields; I figured we'd need it to support this kind of broadly categorized display. Will explain more in a separate issue.)

Whatever we decide here kind of spills over into how tags behave on the code detail pages too.

**Comment by kissane** [comment]
Hmmmmmm. I'm inclined toward the simplest possible version of this:

> We leave the tags as links, and provide an alternate "basic list display" of matching code items when someone clicks on one. (Removing the "Featured" block and replacing the "Explore" block?)

…but my mind is changeable. It seems like tags may indeed be useful nav aids, so I hesitate to unlink them. @ryanpitts, do you have opinions on this behavior?

**Comment by ryanpitts** [comment]
Yep, that would be my first choice as well. @beep does it feel like there will be an article list module that might be the right thing to crib from here?

**Comment by beep** [comment]
> @beep does it feel like there will be an article list module that might be the right thing to crib from here?

@ryanpitts We don’t have one _as such_, but I could whip something up. Maybe I could modify this bit from the featured repo page?

<img width="856" alt="screen shot 2017-01-23 at 2 48 39 pm" src="https://cloud.githubusercontent.com/assets/124493/22220030/15c82968-e17b-11e6-8bf8-14868b910e01.png">

How would that sound to you and @kissane?

**Comment by ryanpitts** [comment]
I dig it

**Comment by kissane** [comment]
Super good is how it sounds to me

**Comment by beep** [comment]
lo, i have issuéd: #24 

I’ll try to get this in for Wednesday!
