### ISSUE TITLE
Articles are missing their tags

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#140]
Not sure why it took me until today to remember this, but it looks like most articles since we redesigned aren't displaying their tags in the left margin, but older articles (https://source.opennews.org/articles/what-i-learned-researching-newsroom-and/) are. @ryanpitts, any sense of where they mighta got to?

**Comment by tsl-lindsay** [comment]
Oh gosh! I noticed this too and kept forgetting to mention it.

**Comment by kissane** [comment]
Yeah, same, my brain triaged it down without permission.

**Comment by ryanpitts** [comment]
ugh, so this goes back to the fateful decision where we split "concept" and "tech" tags into two separate fields, for which I will always bear a small amount of ill will toward slifty. Not enough ill will to be like actual _malice_ or anything, but just enough to regularly remind him that his hoodie sleeves are different lengths.

There's supposed to be an automatic task on article save that compiles those two tag lists into a single list for display, dumps it into an uneditable "Tags" field, and _that_ is what the template draws from. But it looks like that task isn't firing.

![screen shot 2017-03-30 at 12 55 15 pm](https://cloud.githubusercontent.com/assets/56477/24523618/7824b8aa-1548-11e7-8ce9-c8187a39026e.png)


I'll have to investigate why.

**Comment by kissane** [comment]
I am so sorry and also I feel this is a perfectly precision-calibrated level of ill will toward slifty, both for this and in general.

**Comment by kissane** [comment]
tiny bump for after srccon session sorting

**Comment by ryanpitts** [comment]
appreciate the reminder -- putting this on the list for first half of the week

**Comment by ryanpitts** [comment]
this is fixed in https://github.com/OpenNews/opennews-source/commit/8457d7577f680f703282d0cea68bef2a7ab93844 and pushed to staging, ready for production on Monday

**Comment by ryanpitts** [comment]
fwiw, this bug popped up because of recent updates to Django, which no longer does anything with the value of readonly fields in the admin. Which is a sensible way of doing things for sure, just meant I needed to do things a bit differently to compile that merged tags field.

**Comment by ryanpitts** [comment]
(btw this works when you save an article, so will just require a quick tour through recent articles hitting "save." I'll do this after we push to production.)

**Comment by kissane** [comment]
I can help!

**Comment by ryanpitts** [comment]
all done
