### ISSUE TITLE
broken links on profiles

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#141]
report from reader, and I have confirmed—these used to be working, so I'm not sure when they broke.

> I also notice that the github links on people or organization detail pages are broken relative URLS (https://source.opennews.org/people/dan-hill/danhillreports, https://source.opennews.org/organizations/austin-american-statesman/statesman)

**Comment by ryanpitts** [comment]
bah, turns out it's helpful to have the domain in the `href` property too

**Comment by ryanpitts** [comment]
have a fix for this, but let's try to catch #139 in the same update?

**Comment by kissane** [comment]
I'm not actually sure what to do with #139, since I've still never seen whatever situation it is that makes it look like stuff isn't bold. Hmmm.

**Comment by ryanpitts** [comment]
ok, this one's fixed in https://github.com/OpenNews/opennews-source/commit/e050ca8efcdb0a7e0db182ba302b8970ed023bdb and deployed to prod
