### ISSUE TITLE
Link to more articles from homepage under thumbnails

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#145]
It would be super-nice to have a text link to more articles after all the thumbs and titles on the homepage, just to the Articles main page.

**Comment by ryanpitts** [comment]
@kissane so probably something like "See more people ->" here? Below the last line of thumbnails, flush right within the homepage grid container?

![screen shot 2017-12-13 at 5 05 10 pm](https://user-images.githubusercontent.com/56477/33970443-f94aaee4-e027-11e7-9f52-be329cf9e142.png)

**Comment by ryanpitts** [comment]
Which would give us:

![screen shot 2017-12-13 at 5 24 10 pm](https://user-images.githubusercontent.com/56477/33970908-80447fa4-e02a-11e7-8574-14b1dde664d6.png)

**Comment by kissane** [comment]
Yes, that would be perfection!

**Comment by ryanpitts** [comment]
OK, all done pushed to production
