### ISSUE TITLE
add testing domains to Typekit account

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#16]
Can we add https://opennews-source-staging.herokuapp.com and https://opennews-source.herokuapp.com for now? I'm happy to do it, but I don't think I have the login.

**Comment by beep** [comment]
Done! The full list of domains is now

- local.source
- localhost
- sourcedev.ethanmarcotte.com
- opennews-source-staging.herokuapp.com
- opennews-source.herokuapp.com

Let me know if that clears up the issue?

(Related: this is currently on a kit I set up, but I assume we’ll want to transition to a Source-owned kit before launch? I can open an issue for that.)

**Comment by ryanpitts** [comment]
Yep! Haven't pushed anything to the prod instance, but working fine on opennews-source-staging, so I'm sure we're good.
