### ISSUE TITLE
Migrate to a Source-administered Typekit

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#17]
Per #16: before launch, we should migrate over to a Source-owned Typekit…kit. Once a new kit’s in place, we just need to update the `SRC.config.typekit` value in `js/config.js`.

We can make this switch at any time, but I’d recommend waiting until integration/QA is under way. That’d help me evaluate if we can slim down the number of typefaces we’re currently using. But! The switch can toooootally happen any time.

**Comment by ryanpitts** [comment]
Yep, +1 to waiting on this if it smooths out current work.

**Comment by beep** [comment]
Oh hey I forgot about this

Technically, this can wait until post-launch, since my Typekit plan has unlimited pageviews. But if you’d like to move things over earlier, I can help coordinate.

**Comment by ryanpitts** [comment]
Sure, let's get this migrated! I assume I just need to:

1. update the value for `SRC.config.typekit` in `config.js`
2. run `grunt concat` and `grunt uglify`
3. commit?

**Comment by beep** [comment]
@ryanpitts I suppose `step #0` would be to set up the new kit with the same fonts, but yep! That’s it!

**Comment by ryanpitts** [comment]
@beep hahaha yes, step 0 seems important. I don't know that I have access to our Typekit account -- does @kissane perhaps? Or did she add you to ours by any chance?

**Comment by beep** [comment]
@ryanpitts Oh, this is just a kit on my own account. If you’d like to give me access to your Typekit account, I can set everything up.

But if you all would rather do it yourself, here are the fonts we’re currently using:

- [Freight Text Pro](https://typekit.com/fonts/freight-text), specifically:
  - [Medium](https://typekit.com/fonts/freight-text/details/freighttext-pro-medium)
  - [Medium Italic](https://typekit.com/fonts/freight-text/details/freighttext-pro-medium-italic)
- [Sofia Pro](https://typekit.com/fonts/sofia), specifically:
  - [Regular](https://typekit.com/fonts/sofia/details/sofia-pro-regular)
  - [Regular Italic](https://typekit.com/fonts/sofia/details/sofia-pro-regular-italic)
  - [Medium](https://typekit.com/fonts/sofia/details/sofia-pro-medium)
  - [Bold](https://typekit.com/fonts/sofia/details/sofia-pro-bold)
  - [Bold Italic](https://typekit.com/fonts/sofia/details/sofia-pro-bold-italic)

**Comment by ryanpitts** [comment]
OK, we should be swapped over to an OpenNews typekit account. Working great locally, will go up to staging next time I push!

**Comment by ryanpitts** [comment]
@sinker did ask if we fully explored ALL our font options, and suggested https://typekit.com/fonts/hobeaux-rococeaux

**Comment by beep** [comment]
y’all should go [lobster](https://typekit.com/fonts/lobster) or go home

**Comment by kissane** [comment]
for body type right? I approve.

**Comment by beep** [comment]
![ok good talk](https://i.imgflip.com/bcgpr.jpg)

**Comment by beep** [comment]
@ryanpitts Just while I’m thinking of it: does the new Typekit, uh…_kit_ have the final production domain on it?

(#108 just made me think of it. Sorry I didn’t ask earlier.)

**Comment by ryanpitts** [comment]
yarp, we're hitting them all:

> source.opennews.org, localhost, 127.0.0.1, opennews-source-staging.herokuapp.com, opennews-source.herokuapp.com

**Comment by beep** [comment]
i should’ve known you had this well to-hand, my apologies, ok bye `/relurks`
