### ISSUE TITLE
Editorial: updates to Code landing page

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#21]
A couple new things in place to support the organization of the new code landing page.

### Details
* **Featured Repos:** Each Code record has an `is_featured` property, displayed as a "Featured repo" checkbox on the admin form. You can also check/uncheck a group of records all at once from the admin list page (note the "Save" button at the bottom of the list to store those updates).

The "Featured Repos" section of the page shows a random set of three records where `is_featured` is True (and caches that group for 15 minutes along with the rest of the page). We can refine this logic later on in order to, say, favor records that were added recently, but that will be better to do after relaunch.

Each record in this section displays a screenshot if one is available, automatically sized to 300x200. If no screenshot is available, a default logo image is shown instead.

* **Explore All Code:** Each Code record has a `grouping` field, where you can add a primary category that will be used for grouping in the "Explore" section. This `grouping` field can also be edited from the admin list page, so you can update multiple records at once (again, note the "Save" button at the bottom of the page).

The "Explore All Code" section of the page shows links to every code record we have, so long as it has a `grouping` value. Records with no `grouping` are still accessible via direct URL, but won't appear on the list page, so they're effectively hidden. The group headings in this section of the page are sorted alphabetically.

For now, I've written a one-off script that pre-populated each record's `grouping` based on its tags. The script favors the first item in the record's `concept_tags`, falls back to the first item in its `technology_tags`, and finally falls back to leaving `grouping` blank.

### Editorial needs
I've added test data to support each of these new features so things don't look too far off as we work through the redesign. But when we get closer to relaunch, I'll need to wipe that database and reload based on the current production data for Source. (Side note: We should come up with a timeline and plan for that.)

Once that happens, we'll need to:
* Checkmark a selection of records as `is_featured`
* Add more screenshots to the database (we don't seem to have a lot), ideally sized to 600x400
* Edit the `grouping` values in the database to a smaller and more appropriate set of keywords, and make sure each record is assigned to one. I can re-run the pre-population script to kickstart this if we want, but I'm sure there's a better taxonomy we can use.

**Comment by ryanpitts** [comment]
Flagging this for any thoughts or red flags @kissane / @beep

**Comment by kissane** [comment]
This all seems really well thought out, @ryanpitts. It sounds to me like we'll want to plan out a day or two that is just the data migration and correction/population time. Holler when you have some from admin brain and we can map out a plan.

**Comment by beep** [comment]
I see no red flags here, @ryanpitts! What you’ve drafted above sounds eminently sensible. (But if any design changes come out of this, just holler at me.)

**Comment by ryanpitts** [comment]
@kissane do you and @tsl-lindsay have a document anywhere where you're tracking editorial data todos?

**Comment by kissane** [comment]
@ryanpitts We have a bunch of issues in the Source editorial repo, I was thinking I'd scoop them up and make a fresh one here with a punch list.

**Comment by ryanpitts** [comment]
Yeah that seems awesome. In my ideal world, we'd pick a date a week or more from the transition and call a temporary break in publishing so a final data migration can happen with plenty of time left for all this work.

Realistically I know that's not practical to go that long without adding new articles ... but maybe we can talk about a time frame where we'd be OK with a little bit of duplicated work? Do a final data migration, and then publish anything new in both spots?

**Comment by kissane** [comment]
Lindsay and I just went over the plan on our Monday call, so we're prepared to largely go dark on Source after the final data migration—we're going to be working quite hard on launch content and data housekeeping in that final week, so I don't think we really have capacity to be publishing new prelaunch things after the migration anyway. We may have one or two things to produce in both places, but I think a lot of that depends on when exactly the transition falls—a Friday transition is very different, editorially, from a Monday one, etc.

**Comment by ryanpitts** [comment]
Sounds great. Hopefully we can choose a data migration day soon? (I can literally run this at any moment.)

**Comment by kissane** [comment]
Yeah, I hope so—Erika says they're speaking with Knight this week and hope to learn when the announcement will be so we can schedule our things. I'm super-antsy to get this stuff on the calendar.

**Comment by kissane** [comment]
Update from a conversation with @erikao this morning: Dan is nudging the Interested Parties to see if we can lock in a Knight/Moz announcement/launch date, but there's no guarantee we'll have that settled as soon as we'd like.

So the new plan is this: we schedule the site launch (and thus the Final Migration) the moment we know when the announcement will be. If there's not a week of notice between that moment and the announcement itself, we push the launch as needed to give ourselves a full week. That way we're guaranteed sufficient QA and settling-in time even if Knight and Mozilla give us only a day's notice or something absurd like that.

**Comment by ryanpitts** [comment]
OK, I'm definitely more comfortable with us guaranteeing ourselves that week of QA.

**Comment by kissane** [comment]
Yeah, we can't be vulnerable to so many whims!
