### ISSUE TITLE
Template integration: feedback on article_detail template

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#22]
Article detail pages are available on the [redesign staging site](https://opennews-source-staging.herokuapp.com/)! Live data! Woo!

Any article link [here](https://opennews-source-staging.herokuapp.com/) will open into the new templates. A few things I'm noticing:

* I dropped in the pubdate style "November 22, 2016" as I was pulling bits of code forward from existing templates, but now I notice in the mockups they're styled as "22 November 2016"
* we have some prettttttty long tag names in a few places, which may not be excellent in the left column ([example](https://opennews-source-staging.herokuapp.com/articles/low-budget-natural-language-processing/)).
* also in [this example](https://opennews-source-staging.herokuapp.com/articles/low-budget-natural-language-processing/), the code blocks are awfully hard to read. Looks like we have instances where things are just wrapped in `<pre>` rather than `<pre><code>` as in the mockups, which may be causing this?
* our Person records don't have a `website` field, per se, to populate the "Visit website" link down in the author bio section. They _do_ have an arbitrary set of PersonLinks that can be attached to each record, though ... but I'm not sure how we've been using them. I could theoretically pluck the first PersonLink (if one exists) and drop that URL into that spot in the template, or we could add a specific `website` field and drop the PersonLinks, or ...?
* in [this example](https://opennews-source-staging.herokuapp.com/articles/peer-reviewing-our-data-stories/), note under the subheads where we have some `<strong>` lines directly under one of the `<h2>` subheads in the article body. Looks maybe a little awkward? Not sure if this is a common case, and possibly not worth worry about because we wouldn't style things in this way in the new design?

Anyway, just a few things I noticed as I was implementing. But holy wow do I love seeing the articles in the new design. GORGEOUS.

Thought it might be worth opening an issue for people's feedback as templates are integrated against live data.

**Comment by kissane** [comment]
God, this is so pretty. I love it so much.

My responses in approximately the same order as your notes:

-  "November 22, 2016" is just fine, I think I picked up the Commonwealth style based on the SRCCON site that Dan styled that way, but we're a US publication, so we should do it M D, Y 
- Those long tags tho. What are our options there? It seems like we do need to sometimes writer longer tags.
- We should always be using `<pre>` and `<code>` together, so this is a style inconsistency we'll need to look for after the migration. @tsl-lindsay, could you check that out in Pietro's article as it stands on the live site? We can fix that one now and others as they appear.
- We always use the person link for a personal/professional website where they exist, so plucking that one for this use should be seamless. (It somehow won't quite be, but let us pretend.)
- Re: the strong text under the subhead, yep, that's another style inconsistency—our style is always straight text under subheads, so we don't need to adapt the design around that.

**Comment by beep** [comment]
Eep! I totally missed this issue. Sorry to keep you waiting, @ryanpitts and @kissane!

Ryan, this is looking _lovely_. Beautiful work on the integration, sir. This is so, so exciting to see.

I’ll do a firmer pass after tomorrow’s delivery, but for now, a couple thoughts:

> Those long tags tho. What are our options there? It seems like we do need to sometimes writer longer tags.

That’s on me. That element should have a width on it, but doesn’t, so! I’ll open an issue. Would something like this be okay?

<img width="315" alt="screen shot 2017-01-24 at 1 07 30 pm" src="https://cloud.githubusercontent.com/assets/124493/22260165/267d8b8e-e236-11e6-97b8-b2c045d03d2e.png">

(Sorry about that, folks.)

> Re: the strong text under the subhead, yep, that's another style inconsistency—our style is always straight text under subheads, so we don't need to adapt the design around that.

@kissane If it’d be helpful to have some style for sub-subheds, or `significant text immediately beneath subheds`, let me know.

**Comment by kissane** [comment]
>  That element should have a width on it, but doesn’t, so! I’ll open an issue. Would something like this be okay?

Perfection!

> @kissane If it’d be helpful to have some style for sub-subheds, or significant text immediately beneath subheds, let me know.

You know, having this for fallbacks is a nice idea, but only if it will take you less than 5-10 min, for real.

**Comment by beep** [comment]
> You know, having this for fallbacks is a nice idea, but only if it will take you less than 5-10 min, for real.

One idea would be to move our light red into article `h2`s, and give `h3`s a slightly more muted style.

<img width="670" alt="screen shot 2017-01-24 at 1 17 27 pm" src="https://cloud.githubusercontent.com/assets/124493/22260538/8db2c584-e237-11e6-910e-2079b2e48825.png">

Seems to me there’s some decent contrast there. Would that work, do you think?

**Comment by kissane** [comment]
I like that SO much, @beep.

**Comment by ryanpitts** [comment]
+1

**Comment by ryanpitts** [comment]
@kissane re: this

> We always use the person link for a personal/professional website where they exist, so plucking that one for this use should be seamless. (It somehow won't quite be, but let us pretend.)

Do we still care to have a PersonLink model where we can add arbitrary numbers of links to people's profiles? That was the original model spec, but if that's not how we use it ...

If it would be simpler to add a `website` field to the Person model itself, I can do that. If it's easier to just leave current things alone, also fine.

**Comment by kissane** [comment]
> Do we still care to have a PersonLink model where we can add arbitrary numbers of links to people's profiles? That was the original model spec, but if that's not how we use it ...

If we can leave it as-is, I think it's great because I do sometimes add portfolios or other things as additional links. Maybe use guide text to explain our usage, with main website added first? IDK.

**Comment by beep** [comment]
> One idea would be to move our light red into article h2s, and give h3s a slightly more muted style.

This has been fixed in 617bab37ecfdd5992141e645fb08971304d80da7! Thanks for the feedback, @kissane @ryanpitts.

**Comment by kissane** [comment]
👏👏👏👏👏👏👏👏

☺️

**Comment by beep** [comment]
Just noticed this on https://opennews-source-staging.herokuapp.com/articles/what-youve-been-making-nov-9/:

<img width="273" alt="screen shot 2017-01-26 at 3 21 45 pm" src="https://cloud.githubusercontent.com/assets/124493/22348830/2fa650d2-e3db-11e6-81b9-5c7f2c34ca05.png">

That’s on me, @ryanpitts: `.hed-category` changed to `.hed-sub` in the work for #8, and I totally neglected to log that. Just fixed that in f3e36f42d1b6ccc011ff2b48c30d3f9d3db9e260; I’ll open a PR now. Sorry!

**Comment by kissane** [comment]
Mssr @ryanpitts, I think we have made a small error up-thread. @beep changed the display style/colors on subheds just as planned, but it looks like you and I both gave him the wrong specifications for it, because our Source articles currently use H3s as the largest subhed within articles, and H4 as the next-largest. We told him H2 and H3 above, so right now we're missing out on the largest style entirely because none of our articles are marked up with H2s.

Will it be a simple thing to make the (sorry for using color names here, Ryan) red style currently assigned to H2 into an H3 style, and bump the smaller grey style to H4 instead? My apologies for not spotting this!

**Comment by beep** [comment]
@kissane That’s a very easy fix, CSS-wise.

@ryanpitts, I’m happy to make the change, or point you to the relevant spot. Lemme know!

**Comment by ryanpitts** [comment]
mm, I think it would be really helpful for me to have a quick walkthrough about updating styles without blowing things up :)

**Comment by beep** [comment]
> mm, I think it would be really helpful for me to have a quick walkthrough about updating styles without blowing things up :)

That sounds great!

…though actually, i guess this gets into a whole `install grunt on your workstation` thing, which is maybe not the thing we want to get into right now, hmm hmm

@ryanpitts How about this: I’ve opened an issue to flesh out a proper README today. #76 (Which I should’ve done earlier, mea culpa.) I’ll make this change for now, but if there’s another opportunity this week for you to make some JS/CSS edits, we can do a walkthrough over email/Skype/phone/whatever?

**Comment by ryanpitts** [comment]
big ups to README, but also I do have grunt. Probably out of date though?

> grunt-cli: The grunt command line interface. (v0.1.13)

**Comment by beep** [comment]
Nice! That’s what I’ve got!

```
$ grunt --version
grunt-cli v0.1.13
grunt v1.0.1
```

Okay, so:

1. Run `npm install` in the repo root.
2. Once (if?) that finishes, run `grunt`.
3. That’ll chug for a bit, but it should open up `http://localhost:3000/` in your browser once it’s done.

The static templates are in `/tmpl/`, along with their raw scss, js, and image assets. Any edits you make to those assets will kick off another grunt build, and should automatically reload the page.

**Comment by ryanpitts** [comment]
hmm I only show:

```$ grunt --version
grunt-cli v0.1.13```

which seems weird

**Comment by beep** [comment]
Oh, one item I forgot: (heh, sorry, README forthcoming)

1. The `criticalcss` task assumes the static templates are available for view at `http://local.source/tmpl/`.
2. If you don’t feel like monkeying with your virtual hosts (presumably because you are a sane, caring human being), I’d recommend commenting out [the `criticalcss` line item in the default `build` task](https://github.com/OpenNews/opennews-source/blob/master/Gruntfile.js#L268).

**Comment by beep** [comment]
Just noticed there’s a slight timing issue with the comment count (#7) on staging: it usually loads just fine, but sometimes, it blanks out. 

I don’t think this is a blocker, personally, but I’ll try to look into it today. (Happy to bump up the priority, if you’d like.)

**Comment by ryanpitts** [comment]
@beep seems like this one is maybe safe to close, or are you still seeing the issue? I did move the disqus vars ahead of the `initial.js` load on those templates.

**Comment by beep** [comment]
@ryanpitts I haven’t seen it recur recently, so I think we can safely close this. We could always open another issue, if need be.

**Comment by ryanpitts** [comment]
👍
