### ISSUE TITLE
Submit repo: field questions

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#23]
Hey @kissane, when you have a minute:
 
<img width="498" alt="screen shot 2017-01-23 at 12 03 58 pm" src="https://cloud.githubusercontent.com/assets/124493/22214111/81b584b6-e164-11e6-9d27-12bf6b57831e.png">

I’d like to make sure these fields are labeled accessibly; could you give me a breakdown on what each field will contain?

My current working theory:

> **What is it?** `[Name of software package]` is a `[kind of software package]` that `[purpose of software package]`.

> **Who made it?** `[Freeform field for name(s) of creator(s)]`

Is any of that right? Thanks!

**Comment by kissane** [comment]
That is basically all perfect, @beep. I would say:

> What is it? [Name of app/tool] is a [what the app/tool is] that [what the app/tool does, and for whom].

> Who made it? [Freeform field for name(s) of creator(s), optionally including organization name]

**Comment by kissane** [comment]
Just imagine that I formatted that properly. Isn't that a nice thing to imagine?

**Comment by beep** [comment]
@kissane I could not have markdownéd it more perfectly than that.

(Thank you!)

**Comment by beep** [comment]
@kissane I could use a little interaction/design feedback, if you get a moment. Specifically, on this bit:

<img width="488" alt="screen shot 2017-01-23 at 3 49 17 pm" src="https://cloud.githubusercontent.com/assets/124493/22222092/83234af8-e183-11e6-832f-c20cb4ee7dcd.png">

On a scale of `1` to `ethan you should stop doing web design`, what do you think of something like this:

![chooser](https://cloud.githubusercontent.com/assets/124493/22222213/fc411974-e183-11e6-834f-b2339cd1767d.gif)

The emoji are totally replaceable—I’m using Twitter’s CC-licensed emoji, but we could use any icons—but how would something _like_ this be, instead of regular ol’ radio buttons? Too much Whimsy™?

**Comment by kissane** [comment]
I loooooooooove this. I'll probably tweak the language to match the Whimsy Level™ you select, but I love the idea—it's a great place to be doofy on the site. And I am pro-doof.

**Comment by beep** [comment]
Marvelous. Thanks for the feedback, Erin! I’ll keep it for now. (And I’ll add Twitter’s emoji to the final list of software licenses, too.)

> I am pro-doof.

i mean i assume that’s how i got this jorb

**Comment by kissane** [comment]
![nope](https://cloud.githubusercontent.com/assets/1910034/22222527/35242a3c-e185-11e6-94e1-fadc71d791ef.jpg)

**Comment by kissane** [comment]
I'm just going to use that at every opportunity. Be warned.

**Comment by beep** [comment]
here 4 it

![](https://bukk.it/bloompbloompbloompbloompbloompbloompbloomp.gif)

**Comment by ryanpitts** [comment]
@beep it looks to me like this is validating the form on the front end, so I shouldn't wire up server-side validation. Is that right?

**Comment by beep** [comment]
@ryanpitts: The red blocks in the template are just samples of what error messages could look like, style-wise. I haven’t tossed in any `required` attributes into the markup, and haven’t done any JS validation.

I can do both of those things, of course! But I usually recommend them as complements to server-side validation. I defer to you, though.

**Comment by ryanpitts** [comment]
@beep ah! No problem then, Django is actually pretty handy with defining forms and automatically handling validation. Shouldn't need to do things on the js side for such a simple form, I think. I just saw a few bits in the js that made me wonder if validation was happening.

**Comment by beep** [comment]
@ryanpitts Ah! Sorry for the confusion: that’s a little (overwrought) JS I tossed together to assemble some of the sentence-ish parts of the form.
