### ISSUE TITLE
Editorial-side data housekeeping master thread

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#26]
- [x] Column and Learning tagging/categorization—how are we handling this?
- [ ] Make the taxonomy for code repos—"edit the grouping values in the database to a smaller and more appropriate set of keywords, and make sure each record is assigned to one" (Reference: https://github.com/OpenNews/opennews-source/issues/14)
- [ ] Audit/edit existing tags to reduce redundancy
- [x] Do we want to add these, @ryanpitts? http://ogp.me/
- [ ] Do a full audit on remaining image problems, and repair what can be repaired
- [ ] Add headshots on file for authors, collect additional headshots
- [ ] Select repos to feature
- [ ] Audit repos for busted embedded GH repo blocks and fix them
- [ ] Add more repo screenshots/art, focusing first on featured repos

**Comment by ryanpitts** [comment]
Seems like we would want to add OG tags, but I'm not positive how useful they are these days. I'd be super curious to hear what @beep thinks.

**Comment by beep** [comment]
Personally, I’m pro-Open Graph tags, but mainly because I’m a sucker for link previews on Twitter/Slack. I don’t know how _useful_ they are, though!

**Comment by kissane** [comment]
Link previews in Slack and on Twitter are pretty useful for us, since that's where most of our readers hang out—I'd vote yerp

**Comment by ryanpitts** [comment]
Spun OG tags off into a new issue https://github.com/OpenNews/opennews-source/issues/29

**Comment by kissane** [comment]
@tsl-lindsay, I will leave this here for you: I think our best move on the audit is to straight-up look at everything on the site. Which is a good thing to do, from time to time, and now is that time. There are about 600 articles, and we can reserve the bulk of our time for the most recent 250 or so plus the older ones with the highest traffic, but we should glance at the rest and have a tracking spreadsheet for recording problems and their fixes. 

If you have any Source time on Friday, do you think you could take a crack at organizing such a spreadsheet and splitting up articles with me so I can dive in on Monday morning? NBD if not!

**Comment by kissane** [comment]
now redundant, closing
