### ISSUE TITLE
Repo on profiles

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#28]
@kissane, a question about this bit on [the profile page](https://wireframe.cc/rUtpC1):

<img width="450" alt="screen shot 2017-01-23 at 5 49 20 pm" src="https://cloud.githubusercontent.com/assets/124493/22226367/48b29822-e194-11e6-8ff6-e6896a8945d6.png">

Is this the same repository browser as on the featured repo page (https://github.com/OpenNews/opennews-source/issues/8#issuecomment-273805644)? Will we show just one repo, or are there potentially multiple repos on this page?

**Comment by ryanpitts** [comment]
I wonder whether we should drop this from the Person profile page? Seems like an awkward piece of data to try to manage -- which is the most representative GitHub repository for a particular person, right? Unless I'm not remembering right and this is intended to be something else.

**Comment by beep** [comment]
@ryanpitts That makes sense to me. I’ve left it off the profile page for now:

![screen shot 2017-01-24 at 13 52 37-fullpage](https://cloud.githubusercontent.com/assets/124493/22261823/6806c2a4-e23c-11e6-9af8-78c0c73b3de7.png)

…_but_ I can totally toss it back in there if you and @kissane’d like it there. (It’ll just take a little JS work. Ain’t no thing.)

**Comment by kissane** [comment]
I'm so content to leave it off here.

**Comment by beep** [comment]
Sounds great! Closin’.
