### ISSUE TITLE
Comps, v2!

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#3]
@ryanpitts, @kissane—hello! I’ve got another round of comps for you to look at.

(I know the Source and OpenNews logos are coming later today, but thought I’d get these over to you a little early.)

As before, the comps are in Dropbox; I’ve uploaded them here:

> https://www.dropbox.com/sh/tbhmo00ykv6hkit/AADc-TANRprITSGdWmna8HBHa?dl=0

There are six mockups, with two color variations (more below); specifically, we’ve got

1. [The article page](https://www.dropbox.com/s/2c15nc1xcj2s51k/01%20Article.png?dl=0),
   1. [The article page, with a missing lead image](https://www.dropbox.com/s/025fkvyq26ig7d7/02%20Article%20-%20with%20missing%20lead%20image.png?dl=0)
1. [The code landing page](https://www.dropbox.com/s/pr5zqz11irymr2k/03%20Code%20Landing.png?dl=0),
   1. [The code landing page, with the search field open](https://www.dropbox.com/s/wf5aihq8lp6vkyx/04%20Code%20Landing%20-%20search%20open.png?dl=0)
1. [The small screen view of the code landing page](﻿https://www.dropbox.com/s/dp73wc9650trnx3/05%20Code%20Landing%20%28small%29.png?dl=0),
   1. [The small view of the code landing page, with the nav open](https://www.dropbox.com/s/whrok6fhv6ystc9/06%20Code%20Landing%20%28small%29%20-%20nav%20open.png?dl=0), and finally,
1. Two color variants, of the [article](https://www.dropbox.com/s/nd3xikzwfsvh1yv/Color%20Variant%20-%20Article.png?dl=0) and [code landing](https://www.dropbox.com/s/kkivub4trapptuv/Color%20Variant%20-%20Code%20Landing.png?dl=0) pages.

As before, I thought I’d write up a few notes for the team’s review:

- I think tweaking the color palette was absolutely the right call. I’ve introduced a little more red to our main blue—it’s not quite full violet (_never go full violet_), but still feels nicely distinct from where we were. Would love to hear your thoughts.
   - But! If that _still_ feels a little too 🇺🇸🇺🇸🇺🇸, I think we could go in the other direction and desaturate things slightly. In the [article](https://www.dropbox.com/s/nd3xikzwfsvh1yv/Color%20Variant%20-%20Article.png?dl=0) and [code landing](https://www.dropbox.com/s/kkivub4trapptuv/Color%20Variant%20-%20Code%20Landing.png?dl=0) variants, we’re leading with a more slate gray-ish approach. Personally, I like the ~blue better, but think this alternate works nicely, too.
- Also, thanks for calling out the hed/byline order on the Article page. I’ve switched to a more conventional hierarchy, and think it landed in a great place—what do you all think?
- Speaking of articles, I dropped in the default Disqus elements, and found they sit really nicely in our design. If you’d like to make more significant changes, I think this will work fairly well. (But! We can definitely discuss those more significant changes, though!)
- In the search bar, I’ve retitled the story tease “From our Archives”, which should work nicely for a randomized article teaser. How does that feel to you all?

Phew! Long list is long, apologies. That said, I think those are all the big ticket items; all the rest of your notes, suggestions, and feedback from v1 should be incorporated in this round.

Thanks so much for your time, friends. Looking forward to hearing your feedback, and moving onto prototypes!

**Comment by kissane** [comment]
Thank you so much! Before I look, let me remember to post the logos Dan passed along!
[source_vector-1.pdf](https://github.com/OpenNews/opennews-source/files/702534/source_vector-1.pdf)
[open-news-2017.pdf](https://github.com/OpenNews/opennews-source/files/702533/open-news-2017.pdf)

**Comment by beep** [comment]
@kissane _Amazing_, thank you! I just updated the comps with the proper logos; if you’re still seeing the FPO ones, a reload should clear it up.

**Comment by kissane** [comment]
@beep you are too speedy and too helpful, I am getting nervous, please consider more obstruction

**Comment by beep** [comment]
@kissane it’s all sketch, sketch is v fasts, anyway just wait until we get to prototypings

![how i do htmls](https://bukk.it/mybrand.gif)

**Comment by kissane** [comment]
actual lol

**Comment by ryanpitts** [comment]
yay tweaked blue, yay repositioned bylines, and ohgodpleaseyes to default Disqus elements and not trying to restyle third-party anything

**Comment by beep** [comment]
@ryanpitts yay to everything you just said. Glad it looks good to you!

Excited to hear everyone’s feedback. Thanks again, all.

**Comment by kissane** [comment]
Welp, we love them.

I have been looking at them on and off for several hours and I'm having a hard time finding anything to pick on at all. We all like the grey a lot, but are presently leaning blue (it's SO PRETTY) and I will offer a formal decision and any final notes before morning, but at the moment it's just 😍😍😍😍.

**Comment by beep** [comment]
@kissane that is WONDERFUL news, thank you!

Looking forward to hearing the final word, too. If there are any final design notes, I’d suggest we incorporate them into the prototypes—but of course, if there are any knotty layout questions that pop up, I’m happy to knock out a quick revision in Sketch. Let me know.

![yay](https://bukk.it/heyo.gif)

Yay, folks. _Yay._

**Comment by kissane** [comment]
So, I've tried really hard, but the only note I have is really a note for @ryanpitts cause it's about the page logic—I think when we have an article that's missing a cover image, it should just have no cover on the article page, but that cool dots image as its thumbnail on list pages. Does that make sense?

And we have thought our thoughts and felt our feelings and we say blue, blue, ~'lectric~ violet-tinged blue.

So full prototypical speed ahead, with our happiest thanks! 

💙

**Comment by ryanpitts** [comment]
> I think when we have an article that's missing a cover image, it should just have no cover on the article page, but that cool dots image as its thumbnail on list pages.

yep, I dig it

**Comment by beep** [comment]
@kissane @ryanpitts Well, this is fantastic news! I got started on the prototypes (#4) earlier this morning; I’ll keep you all posted on my progress as I move toward Wednesday.

![](https://bukk.it/blues.gif)

<small>get it because blue</small>
