### ISSUE TITLE
Style needed for inline images?

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#34]
On https://opennews-source-staging.herokuapp.com/articles/low-budget-natural-language-processing/:

<img width="550" alt="screen shot 2017-01-25 at 2 30 43 pm" src="https://cloud.githubusercontent.com/assets/124493/22305803/e447d6c2-e30a-11e6-8281-3b97b58022c1.png">

(ping #22)

**Comment by beep** [comment]
@kissane @ryanpitts When you get a moment, do you have any direction on how you’d prefer to handle elements like this?

**Comment by ryanpitts** [comment]
hmmm, deferring to @kissane here, but seems like vertically aligned to the middle of the text?

**Comment by beep** [comment]
@ryanpitts ah, hmm, yeah, i guess that’d make sense, especially since that’s how they’re styled on [the original article](https://source.opennews.org/en-US/articles/low-budget-natural-language-processing/) huh

`[ahem]`

Related question: I noticed there’s some CSS inlined in the head of that page. Should I pull those rules into the core CSS, or are they one-offs?

**Comment by ryanpitts** [comment]
Looks like that was a one-off (the CMS has a field primarily used for adding article-specific js, but looks like the editor used it to add a bit of extra CSS to this page). Still, seems like a `.noborder` class might end up being useful?
