### ISSUE TITLE
Template integration: feedback on code_detail template

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#36]
Hello hello initial integration done on the repo pages.

For example, [here's one](https://opennews-source-staging.herokuapp.com/code/agate/), or you can hit anything from the [code list page](https://opennews-source-staging.herokuapp.com/code/).

**Comment by beep** [comment]
@ryanpitts you are a _machine_. This is so exciting to see!

From a process standpoint, do you have a preference if I file issues on code detail pages here, or in separate issues?

**Comment by ryanpitts** [comment]
It feels like it could be helpful to keep things corralled into feedback threads for each template, if only for being able to mentally check off "this is done" for each one. BUT, it's far more important to go with a workflow that you find productive, and if that's separate issues that's fine with me too.

**Comment by beep** [comment]
@ryanpitts Keeping stuff corralled sounds perfect to me. Thanks!

**Comment by beep** [comment]
Line wrapping! _My old nemesis._

Noticed this on the detail page, but this affects all `.list-promos` blocks, too:

<img width="828" alt="screen shot 2017-01-26 at 10 54 57 am" src="https://cloud.githubusercontent.com/assets/124493/22340198/936b9b2a-e3ba-11e6-88d4-d79b7d3209ec.png">

Namely, the tops of the tags are uneven across the row.

I could try to mitigate this a _bit_ by enforcing a minimum height on the headlines:

<img width="817" alt="screen shot 2017-01-26 at 11 51 57 am" src="https://cloud.githubusercontent.com/assets/124493/22341386/9a026852-e3be-11e6-99da-a46a59ca0966.png">

Alternately, I could explore other treatments of the content in this module. (Maybe the titles could be pulled into the image somehow? IDK)

This isn’t a bug _per se_, but I did feel compelled to log it.

**Comment by ryanpitts** [comment]
I don't mind the mitigated min-height version, and the odd case where it's a three-line title there just doesn't feel like a huge problem to me. I wonder if it looks awkward when all three promos have short titles, though. Will it feel like a weird gap? Probably not?

**Comment by kissane** [comment]
I'm actually fine with both versions—tags starting at uneven heights and the bumped-down version. They both look clear/legible to my eyes, so I'll leave the decision to youse.

Otherwise, everything is looking just glorious.

**Comment by ryanpitts** [comment]
yeah, honestly I don't mind the uneven heights version either.

**Comment by beep** [comment]
@ryanpitts @kissane Okay, cool! Let’s leave them as-is, then. (But if your opinions change, do let a @beep know.)

**Comment by ryanpitts** [comment]
@beep hmm, the `repo.js` bit seems to be failing. Not sure if anything changed in the js, or if I have something misconfigured in the template: https://opennews-source-staging.herokuapp.com/code/narrative-charts/

**Comment by beep** [comment]
@ryanpitts Hm! It seems okay here:

![screen shot 2017-02-02 at 7 58 18 am](https://cloud.githubusercontent.com/assets/124493/22550297/6980417c-e91d-11e6-801f-c5969490ed4a.png)

Are you still seeing the error? If so, mind hooking me up with a little more info? (Any console information would be very helpful, as would the browser you’re using.)

Thanks!

**Comment by ryanpitts** [comment]
oh hey. Yep, working here now, I wonder if my browser had just cached old js. Seems all good now!

**Comment by beep** [comment]
_phew_ yay
