### ISSUE TITLE
Template integration: feedback on person_detail template

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#37]
Wheeee initial integration done on the people profile pages.

For example, here's [a person](https://opennews-source-staging.herokuapp.com/people/jeremy-bowers/), or you can hit any profile from the [(old template) person list page](https://opennews-source-staging.herokuapp.com/people).

**Comment by kissane** [comment]
Hooray! Notes coming on all of these today!

**Comment by beep** [comment]
@kissane Yay, thank you! Looking forward to hearing folks’ feedback.

**Comment by kissane** [comment]
Only tiny things here.

First, there's a little bit of weirdness with the GitHub and Twitter bugs on the person profile page, at my default browser window width:

<img width="1108" alt="screen shot 2017-01-26 at 12 14 55 pm" src="https://cloud.githubusercontent.com/assets/1910034/22342170/64d6b658-e3c1-11e6-87cf-de4e92ac6a6e.png">

If i make the window bigger or smaller, it makes perfect sense, but the spacing is a little confusing to me at this medium width. Not sure what to suggest, and maybe it's fine?

**Comment by kissane** [comment]
Second thing is what looks like a minor display bug related to the span tags around NPR, here:

<img width="814" alt="screen shot 2017-01-26 at 12 15 29 pm" src="https://cloud.githubusercontent.com/assets/1910034/22342243/b1f091e8-e3c1-11e6-9d6c-3441656be0f5.png">

**Comment by kissane** [comment]
And last is that I'm very very slightly itchy about the spacing above and below these subheads:

<img width="349" alt="screen shot 2017-01-26 at 12 15 48 pm" src="https://cloud.githubusercontent.com/assets/1910034/22342267/c630ba8e-e3c1-11e6-971c-d4850cc72ac6.png">

My brain wants to reduce the spacing below CODE and PROJECTS just slightly to clarify their relationship to the text they're contextualizing, or to give PROJECTS a little more headroom. Right now it feels equidistant between the elements above and below it, and that always makes my lizard brain slightly nervous. Eh? Ehh. Might be fine.

**Comment by beep** [comment]
> First, there's a little bit of weirdness with the GitHub and Twitter bugs on the person profile page, at my default browser window width:

Ah, that’s a great catch—thank you, @kissane. I’d expected there was _always_ going to be an avatar above the social bugs ([e.g.](http://sourcedev.ethanmarcotte.com/profile.php)), which set things off a bit more. I’ll come up with an alternate treatment.

> Second thing is what looks like a minor display bug related to the span tags around NPR, here:

oh well that uh looks great doesn’t it

(Note for @beep, who is about to fix this: https://opennews-source-staging.herokuapp.com/people/jeremy-bowers/, `.list-articles a > *` is bad; why u do a thing)

> And last is that I'm very very slightly itchy about the spacing above and below these subheads:

That’s great feedback, Erin—thanks! How would this feel to you?

<img width="526" alt="screen shot 2017-01-26 at 12 25 01 pm" src="https://cloud.githubusercontent.com/assets/124493/22342477/8b533f6c-e3c2-11e6-85d8-472e8c05c730.png">

**Comment by ryanpitts** [comment]
> Right now it feels equidistant between the elements above and below it

I found myself wondering about that spacing as well.

**Comment by kissane** [comment]
> Ah, that’s a great catch—thank you, @kissane. I’d expected there was always going to be an avatar above the social bugs (e.g.), which set things off a bit more. I’ll come up with an alternate treatment.

Ahhhhh of course—thank you! We should have avatars in place 90% of the time, but a fallback would be a wonderful gift. If it gets too hassle-y, though, please skip it.

> That’s great feedback, Erin—thanks! How would this feel to you?

So happy. Doesn't even need to be that big a change if you think it's better wider, but anything in this range makes me as happy as a human can be in the year 2017.

**Comment by beep** [comment]
> Second thing is what looks like a minor display bug related to the span tags around NPR, here:

Hey @ryanpitts, quick question for you. In the `.list-articles` block on [the template](http://sourcedev.ethanmarcotte.com/profile.php), each entry’s structured like so:

```html
<li>
    <a href="#">
        <img src="/img/fpo/article-teaser.jpg" alt="">
        <h3 class="hed-article-title">Hed</h3>
        <h4 class="hed-article-subhed">Subhed</h4>

        <div class="summary">
            <p>Summary…</p>
        </div><!-- /end .summary -->
    </a>
</li>```

On the integrated template, it looks like we might have a few extra `a` elements:

```html
<li>
  <a href="/articles/link/">
    <img src="blah.jpg" alt="">
    <h3 class="hed-article-title">Title</h3>
    <h4 class="hed-article-subhed">Subhed</h4>

    </a><div class="summary"><a href="/articles/link/">
      </a><p><a href="/articles/link/">Summary…</p>
    </div><!-- /end .summary -->
</li>```

Is it possible to that down to one outermost `a`? Or should I rethink that markup?

**Comment by beep** [comment]
Just pushed a few fixes (6f5d3916773ab2009c6641294961193c595542a0, 7ed7bf78e5ca92378371f36e2d597c578445e907) to fix some of these issues!

@kissane, I opted to move the bugs down below the bio. With avatar:

<img width="1282" alt="screen shot 2017-01-26 at 1 00 35 pm" src="https://cloud.githubusercontent.com/assets/124493/22343797/84d68a04-e3c7-11e6-8142-5449896cb8e4.png">

Without avatar:

<img width="1281" alt="screen shot 2017-01-26 at 1 00 51 pm" src="https://cloud.githubusercontent.com/assets/124493/22343804/8aa5533e-e3c7-11e6-8b26-86319365914a.png">

I liked the association between the avatar+bugs, but I like the straightforwardness of this, too. How’s it look to you?

**Comment by ryanpitts** [comment]
> On the integrated template, it looks like we might have a few extra a elements:

@beep ahhh, I wasn't thinking about this, our article `summary` field allows HTML, and can sometimes contain links to previous articles, etc. Which is great in a lot of cases, but sure doesn't play nicely when the element is already wrapped in an `a` tag. I have a `safe_summary` method that strips those tags for precisely this case though, so I just need to swap that in. Thanks for spotting!

**Comment by kissane** [comment]
> I liked the association between the avatar+bugs, but I like the straightforwardness of this, too. How’s it look to you?

I like both ways, so let's go with straightforward! Thank you!

**Comment by kissane** [comment]
I think we're done here— @ryanpitts?

**Comment by beep** [comment]
I think this looks good, too. The only thing I couldn’t QA is avatar alignment. Do any of the profiles on staging have avatars?

**Comment by kissane** [comment]
@beep They don't unless @ryanpitts sets it up to pull from Twitter as a fallback, which I think is not set up right now?

**Comment by beep** [comment]
@kissane Ah, marvelous. Thanks!

Other than that, I think this looks _g r a n d_

**Comment by ryanpitts** [comment]
@beep just threw one in: https://opennews-source-staging.herokuapp.com/people/ryan-pitts/

**Comment by beep** [comment]
looks SHAHP
