### ISSUE TITLE
Initial integration-ready templates

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#4]
Just opening up an issue for static prototype development, the first round of which will cover

- [x] Article
- [x] Code Landing

**Comment by beep** [comment]
Hi, folks! Apologies for not getting an update to you earlier, but: I’m in the middle of one final big refactor of the masthead, and then I’ve got some light QA to finish up. Once that’s done, I’ll have a PR opened for review.

I’m looking good for tidying these up in a few hours’ time, but I’ll let you know if anything causes that to shift. More anon!

**Comment by ryanpitts** [comment]
Hurray! I'm finishing up some auth-related stuff, so I wouldn't be getting to these till Thursday morning Pacific time anyway, if that's helpful.

**Comment by beep** [comment]
That is helpful to know—thanks, @ryanpitts! I should still be good for getting them  to you tonight, but I’ll holler if anything changes that, and I need to take the morning.

Thanks again. I’ll be in touch!

**Comment by ryanpitts** [comment]
@beep would you have time for a brief call today, so I can run a couple integration questions past you?

**Comment by beep** [comment]
@ryanpitts Absolutely! I’m around until ~5pm (ET). What’s a good time for you to chat?

**Comment by ryanpitts** [comment]
@beep how about top of the hour, 3pm ET?

**Comment by beep** [comment]
_Perfect._ Shall I call you, or would you prefer some sort of Hangouts-y thing?

**Comment by ryanpitts** [comment]
Hangout would be great. I'll drop you an email link in a few!
