### ISSUE TITLE
form value assignment on "Suggest a repo" page

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#42]
Hi @beep, can you tell me how values are assigned when when someone clicks an `li` in this part of the submit a repo form?

![screen shot 2017-01-26 at 1 08 31 pm](https://cloud.githubusercontent.com/assets/56477/22350459/b22e15e8-e3c8-11e6-9803-3de0d4f888b7.png)

I've got this form nearly implemented, but I'm only getting empty values for that field after submit. I'm guessing it might have to do with the slightly different input name/id values I have to use? (Django's form validation is really nice, but I can't name Python elements with hyphens, so everything gets underscores instead. Also some automatic prepending of "id_" for certain attributes.)

Here's your HTML:
```
<ul class="form-chooser choose-repo-difficulty">
    <li>
        <input name="repo-difficulty" id="repo-difficulty-1" value="repo-difficulty-1" type="radio" />
        <label for="repo-difficulty-1" required class="icon-difficulty-1">Super easy</label>
    </li>
    <li>
        <input name="repo-difficulty" id="repo-difficulty-2" value="repo-difficulty-2" type="radio" />
        <label for="repo-difficulty-2" required class="icon-difficulty-2">Pretty easy</label>
    </li>
    <li>
        <input name="repo-difficulty" id="repo-difficulty-3" value="repo-difficulty-3" type="radio" />
        <label for="repo-difficulty-3" required class="icon-difficulty-3">A little tricky</label>
    </li>
    <li>
        <input name="repo-difficulty" id="repo-difficulty-4" value="repo-difficulty-4" type="radio" />
        <label for="repo-difficulty-4" required class="icon-difficulty-4">Kinda hard</label>
    </li>
</ul>
```

And here's mine:
```
<ul class="form-chooser choose-repo-difficulty">
    <li>
        <input name="repo_difficulty" id="id_repo_difficulty_1" value="1" type="radio" />
        <label for="id_repo_difficulty_1" class="icon-difficulty-1">Super easy</label>
    </li>
    <li>
        <input name="repo_difficulty" id="id_repo_difficulty_2" value="2" type="radio" />
        <label for="id_repo_difficulty_2" class="icon-difficulty-2">Pretty easy</label>
    </li>
    <li>
        <input name="repo_difficulty" id="id_repo_difficulty_3" value="3" type="radio" />
        <label for="id_repo_difficulty_3" class="icon-difficulty-3">A little tricky</label>
    </li>
    <li>
        <input name="repo_difficulty" id="id_repo_difficulty_4" value="4" type="radio" />
        <label for="id_repo_difficulty_4" class="icon-difficulty-4">Kinda hard</label>
    </li>
</ul>
```

**Comment by ryanpitts** [comment]
AH! Never mind. This was a derpy problem on my end in form processing. Closing and pretended this never happened.

**Comment by beep** [comment]
@ryanpitts Hm, weird. It _seems_ like it should be fine: the enhanced view of that module is just presenting the `label` elements to sighted users, so after they click on an emoji, the radio button should be selected.

Can you toss the `required` attributes back on the `input`s, and see if that catches it?

**Comment by beep** [comment]
eep sorry ships in the night ignore me!
