### ISSUE TITLE
Template integration: feedback on suggest_repo form/template

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#43]
I have wrestled with email delivery without domain control on Heroku until the breaking of day, and I did not let it go until it blessed me.

Here is an [initial integration of the suggest repo](https://opennews-source-staging.herokuapp.com/code/suggest/) form on staging. You can submit! It will send something to source@opennews.org (and to me)!

**Comment by beep** [comment]
@ryanpitts This looks _great_. I’m seeing a…weird JavaScript error on that page, though; I’ll open another issue.

**Comment by beep** [comment]
Just took another look, now that #54’s resolved. Looks _pret-ty_ great, to me.
