### ISSUE TITLE
Template integration: feedback on person_list template

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#45]
OK, we're just starting to dip into templates that @beep hasn't designed himself. Building from all the awesome modules, I've got an alpha version of the [person list page](https://opennews-source-staging.herokuapp.com/people/).

I say alpha because I'm cribbing from the "featured repos" promos as well as the organization lists underneath article authors, but there's still some massaging needed here. Not really any vertical spacing between rows when the promo items wrap, and the vertical alignment of the icon isn't happy because it's not in an `a` tag.

@beep would love to connect with you as I start applying some of the design to new pages, to get some strategic tips.

**Comment by beep** [comment]
(Sorry for the assignment toggling; trying to keep my assignment on things I’m actively working on, or Actual Bugs.)

Looking at this now!

**Comment by ryanpitts** [comment]
Person list on staging now, looking great https://opennews-source-staging.herokuapp.com/people/

**Comment by beep** [comment]
@ryanpitts that looks _grand_.

A question occurs: do y’all need/want some pagination links?

**Comment by ryanpitts** [comment]
@beep YES. That's going to be crucial on the article_list page in particular, which I should really get on soon.

**Comment by beep** [comment]
@ryanpitts Awesome. On it. #68

**Comment by kissane** [comment]
I am good with this, does pagination need to show up on this page, @ryanpitts? Or are we done here?

**Comment by ryanpitts** [comment]
Hm. We did not paginate the old People page. This does add a lot of photo weight to the page, and yet ... I can't imagine people are going to click through pages of this like a directory. Much more likely they'll land here and do an on-page search? So I think no pagination still? 

I do still need to add the filter form at the top though.

**Comment by kissane** [comment]
This all works for me, and I agree about pagination.

**Comment by kissane** [comment]
Reopened for filter formmmm.
