### ISSUE TITLE
should some of the `.hed-label` flags be links?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#47]
Not sure if we want to support this, but I've unconsciously tried multiple times to click on "PEOPLE" here to return to the people_list page.

![screen shot 2017-01-27 at 2 28 10 pm](https://cloud.githubusercontent.com/assets/56477/22389924/09b59898-e49d-11e6-9c92-e81cab524195.png)

The styles don't support turning that into a link right now, so I'm just raising the question -- should we? @beep @kissane

**Comment by beep** [comment]
Ha, yeah—great question, @ryanpitts. I was wondering if we might leaving ourselves open to that.

So! A couple ramblin’, EOD-Friday thoughts:

- From a CSS standpoint, we can totally make those links, using the existing styles. Just a matter of turning `<h2 class="hed-label">` into `<a class="hed-label" href="…">`. (The hover styles might look a little weird, but that’s an easy fix.)
- That said, if we go that route, we might want to come up with a slightly different style for those linked headers anyway.

Anyway. From a design standpoint, it’s totally doable. I’ll defer to you and @kissane on whether we _should_ have those be breadcrumb-y, though.

**Comment by ryanpitts** [comment]
I tend to fall on the _should_ side, myself.
