### ISSUE TITLE
can we add an .icon-location class?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#48]
@beep Running into a spot where it might be nice to a little map pin icon, next to an Organization's location. Maybe there are other standard icons that might be useful too? This is just the first one I've run into.

**Comment by beep** [comment]
@ryanpitts Yes! I add that in.

Also, would it be helpful for me to write up how to add new icons?

**Comment by ryanpitts** [comment]
> Also, would it be helpful for me to write up how to add new icons?

YESSSSS

**Comment by beep** [comment]
@ryanpitts Done! Also, I accidentally pushed those changes to master, as I am the worst.

But: the icon’s in there, as are [some instructions for adding new ones](https://github.com/OpenNews/opennews-source/commit/7463bb9736ec31ff7927f3d4c9301cbb28e1bdc8#diff-04c6e90faac2675aa89e2176d2eec7d8R5). Do those look okay?

**Comment by ryanpitts** [comment]
@beep Looks great!
