### ISSUE TITLE
 Template integration: feedback on organization_list template 

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#49]
This is not at all done, but I think we need to revisit the [wireframe](https://wireframe.cc/qFIjxi) plan for the organization_list page. @beep @kissane 

I tried using the `promo` module a la the "Featured repos" block, but this grid doesn't work very well:

![screen shot 2017-01-27 at 3 55 07 pm](https://cloud.githubusercontent.com/assets/56477/22392313/88d8447c-e4ac-11e6-9446-161b9a994fae.png)

I also tried manually bumping down the font-size a bit, which is definitely better, but still not great.

![screen shot 2017-01-27 at 3 55 25 pm](https://cloud.githubusercontent.com/assets/56477/22392353/f99de0cc-e4ac-11e6-884a-2375d8639514.png)

Currently the page is deployed using a modified version of the author promo modules at the bottom of the article_detail page. Seems maybe better? Link underline right next to the rule isn't great, and icon spacing for the city needs help (I think that's wanting to be inside an `a` tag, but ...). Anyway, [example page to work from is here](https://opennews-source-staging.herokuapp.com/organizations/).

![screen shot 2017-01-27 at 4 24 14 pm](https://cloud.githubusercontent.com/assets/56477/22392368/1571f3a6-e4ad-11e6-8f84-8211ee61c4b0.png)

**Comment by beep** [comment]
@ryanpitts Oh man, nice work stress-testing these patterns. Exciting to see this come together.

So! First thing, real quick: if you add a `has-icon` class to that `link-main p-org icon-company` element, that should clear up the icon spacing/alignment.

With that out of the way, I kinda dig that linear treatment of the company profiles. But! If you’d like 2- or 3-up grid of profiles here, I can come up with something that should handle it. Let me know.

**Comment by ryanpitts** [comment]
Sweet, that's easy then. I also dig the linear treatment, and I can drop a quick filter at top (was holding off until I knew what the containing elements would be). @kissane does this list format seem ok?

Also, does it feel like there's any weirdness with the underline on the links so close to the hairline below?

**Comment by beep** [comment]
@ryanpitts Oh absolutely, it is _highly_ weird. I’m tweaking the homepage right now, then I’ll take a hard look at that.

**Comment by kissane** [comment]
I like the listness so much, all clear here.

**Comment by beep** [comment]
@ryanpitts @kissane Voilà, updated listiness:

http://sourcedev.ethanmarcotte.com/list-orgs.php

How’s that?

**Comment by ryanpitts** [comment]
ooh yeah, I dig it

**Comment by ryanpitts** [comment]
also big 👍 to a generic .profile object, we will run into that use case all over the place. Already was pondering what to do in search results.

**Comment by beep** [comment]
@ryanpitts Awesome! On that front, I’m going to try to make `.list-promos` / `.src-promo` a little more generic tomorrow, so you can drop in more griddish things _wherevuh_.

**Comment by kissane** [comment]
> @ryanpitts @kissane Voilà, updated listiness:

Looks loooovely, thank you!

**Comment by ryanpitts** [comment]
@kissane this maybe needs some tagline love?

![screen shot 2017-02-01 at 8 23 31 pm](https://cloud.githubusercontent.com/assets/56477/22537094/569e526c-e8bc-11e6-94b4-c561bf455982.png)

**Comment by kissane** [comment]
> @kissane this maybe needs some tagline love?

O but it's so eloquent.

Yeah. 

How bout something like "Newsrooms, civic data orgs, j-schools, and more"

**Comment by kissane** [comment]
Is "j-schools" intolerable? Could use "universities" instead.

**Comment by ryanpitts** [comment]
or we could go with "jfc just do the work"

**Comment by ryanpitts** [comment]
👍 to the one with "universities" though, I'll swap it in

**Comment by kissane** [comment]
on brand

**Comment by kissane** [comment]
fine, be professional Ryan, whatever
