### ISSUE TITLE
Template integration: feedback on homepage template 

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#57]
@beep @kissane we've got it running here: https://opennews-source-staging.herokuapp.com/

Unfortunately the js is currently broken, as noted in #54, so the search bar is rendering below, and other things might be out of whack too.

**Comment by ryanpitts** [comment]
Yoooo, those @beep updates fixed this up great. [HOMEPAGE!](https://opennews-source-staging.herokuapp.com/)

**Comment by beep** [comment]
On the homepage, my clever byline treatment feels pretty good when there’re a bunch of authors:

![screen shot 2017-02-02 at 11 56 34 am](https://cloud.githubusercontent.com/assets/124493/22559321/b6d8deae-e93e-11e6-9daf-a99b74ecf50e.png)

…but it feels…less clever when there’s only one author:

![screen shot 2017-02-02 at 11 55 15 am](https://cloud.githubusercontent.com/assets/124493/22559246/87eeaf56-e93e-11e6-8478-5c4ac5e5426c.png)

I’m wondering if a toggle’d be helpful here, or if I should just stop bottom-aligning the byline.

@ryanpitts @kissane, any thoughts?

**Comment by kissane** [comment]
Let's turn off bottom-aligning, please, just to simplify, and then I may fiddle with adding a short summary in another month with Ryan if we feel springy. THANK YOU, @beep.

**Comment by kissane** [comment]
(I guess this is a Priority 2?)

**Comment by ryanpitts** [comment]
👍 to this plan

**Comment by beep** [comment]
Bottom alignment disabled in e2f655f8fd463e7ef76424227f33b72caeb91d13!

**Comment by kissane** [comment]
Woop! I think we might be closed here?
