### ISSUE TITLE
headline wrapping issue with random promo in search pane

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#60]
Hi @beep, I just implemented the random article promo and ran into this:

![screen shot 2017-01-31 at 5 11 53 pm](https://cloud.githubusercontent.com/assets/56477/22494972/1d457174-e7f1-11e6-8fd0-7c54a5710643.png)

**Comment by beep** [comment]
Oh, ha—thanks, Ryan. I’ll take a look at that.

(Is there a non-breaking space in that headline, btw?)

**Comment by beep** [comment]
Here’s what I’d recommend!

- I’d planned for a smaller/shorter thumbnail in there, so I’d suggest we cap the height of those images in the CSS.
- I’ll bump the type size down a bit at our widest breakpoint.

![screen shot 2017-02-01 at 9 41 21 am](https://cloud.githubusercontent.com/assets/124493/22511128/9c2b8cbe-e862-11e6-9122-a435dff4e73e.png)

Now! If those titles _do_ have `&nbsp;`s in ’em, some weird line breaks might still occur. But! In browsers that support it, we can add a little auto-hyphenation:

![screen shot 2017-02-01 at 9 42 45 am](https://cloud.githubusercontent.com/assets/124493/22511185/ced728da-e862-11e6-805f-51b4d3cf6f4e.png)

Not every browser/device’ll support it, but for those that do, it’ll clean up the heds a bit.

Let me know what you think. If that all sounds good to you, merge https://github.com/OpenNews/opennews-source/pull/63 at your leisure!

**Comment by ryanpitts** [comment]
> (Is there a non-breaking space in that headline, btw?)

@beep ohhhhh, I hadn't connected this, but yes I'm passing headlines (and display text in a number of places) through [a filter called `typogrify`](https://github.com/mintchaos/typogrify) that fixes quote marks and a few other nice things ... including adding an nbsp between the last two words to avoid widows.

In other places I'm just passing text through `smartypants`, which avoids the widow-busting. I'll swap that in here to be safe as well.

**Comment by ryanpitts** [comment]
@beep also, is there a target size I should thumbnail those images to? I can do whatever.
