### ISSUE TITLE
a couple of .has-icon/.profile-links questions

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#61]
1) Wondering if it's possible to nudge the vertical alignment on a `p.has-icon` as well. Use case is on the organization profile pages, where we have a potentially long list of people. If there's a better element, I'm totally up for it, but right now I have a comma-separated list of people inside a `p`:

![screen shot 2017-01-31 at 8 44 45 pm](https://cloud.githubusercontent.com/assets/56477/22495521/2ebe0b14-e7f6-11e6-8492-b4160f5d604b.png)

2) Also wondering if it's possible to do something with `.has-icon` inside of `.src-promo` ... or maybe the real need is for `.profile-links` styling inside those promo modules. Use case is on the community landing page:

![screen shot 2017-01-31 at 8 46 29 pm](https://cloud.githubusercontent.com/assets/56477/22495573/9b108fda-e7f6-11e6-9097-01ca8d30215f.png)

Also completely possible I should be using different elements in these spots!

**Comment by beep** [comment]
Great feedback, @ryanpitts.

1. Yeah, icon alignment definitely needs a little love. I’ll spend some time on this today.
1. I’m working on some fixes for #45, #50, and #61 that should help with this. More soon.

Thanks!

**Comment by beep** [comment]
@ryanpitts #64 has a couple icon-related fixes in it:

- Some [default/global directives for icon placement](https://github.com/OpenNews/opennews-source/pull/64/commits/f603165abcece6a65d11691f80842c82cd28b7fa#diff-e5456831d657b5d9429b12633142afbfR17);
- A new [icon-specific sass partial](https://github.com/OpenNews/opennews-source/pull/64/commits/f603165abcece6a65d11691f80842c82cd28b7fa#diff-e25748a35c194ce85bfad9777f48e5f0) that can be used to be a little more particular about specific icons’ position;
- A number of element-specific icon tweaks

This cleans up a lot of tiny icon issues, and _should_ clear up that profile icon alignment. Let me know how it looks?

**Comment by ryanpitts** [comment]
Yep, I think these cases are looking good

![screen shot 2017-02-01 at 11 57 06 am](https://cloud.githubusercontent.com/assets/56477/22523828/9c2edae6-e875-11e6-94b9-b4060d6fee26.png)
![screen shot 2017-02-01 at 11 56 42 am](https://cloud.githubusercontent.com/assets/56477/22523827/9c2788c2-e875-11e6-8d22-7d2656784b1e.png)
