### ISSUE TITLE
Template integration: feedback on organization_detail template

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#62]
Definitely getting easier to do these as we get further into the process, @beep these modules are so good. Here's an example of an [organization detail page](https://opennews-source-staging.herokuapp.com/organizations/propublica/) to check out.

Only two things I'm noticing:
* We might need an alternate `.profile-photo` that still floats to the right, but doesn't have the `border-radius` (and can handle logos that are fairly horizontal)
* The vertical alignment on the `p.has-icon` in the "People" list, as noted in https://github.com/OpenNews/opennews-source/issues/61

**Comment by ryanpitts** [comment]
yoooo, looking good. Here's [the ProPublica profile](https://opennews-source-staging.herokuapp.com/organizations/propublica/) with the updated logo handling.

Noting that extreme horizontal logos aren't ideal, e.g. [New York Times](https://opennews-source-staging.herokuapp.com/organizations/new-york-times/). Not sure the best approach there, perhaps just an editorial policy of adding whitespace padding in the img itself?

**Comment by beep** [comment]
> yoooo, looking good. Here's the ProPublica profile with the updated logo handling.

dang, that looks _great_. thanks for kicking off these changes, @ryanpitts.

> Noting that extreme horizontal logos aren't ideal, e.g. New York Times. Not sure the best approach there, perhaps just an editorial policy of adding whitespace padding in the img itself?

Hm, yeah. That’s tricky.

CSS-wise, the one thing that comes to mind is we _could_ apply a border and some padding to logos. Here’s a quick sketch:

<img width="1283" alt="screen shot 2017-02-01 at 3 37 09 pm" src="https://cloud.githubusercontent.com/assets/124493/22525207/5419de94-e894-11e6-9976-c59ab03f0264.png
<img width="1279" alt="screen shot 2017-02-01 at 3 38 11 pm" src="https://cloud.githubusercontent.com/assets/124493/22525287/99d3b0ae-e894-11e6-824c-ea7797cfbde5.png">
">

It’s a bit of a brute force treatment—some logos might not look great—but it’s an option.

My bigger concern is how we’d like to handle those logos on smaller screens:

<img width="321" alt="screen shot 2017-02-01 at 3 38 48 pm" src="https://cloud.githubusercontent.com/assets/124493/22525337/c79f47b4-e894-11e6-9d95-5135d2c474c4.png">
<img width="321" alt="screen shot 2017-02-01 at 3 38 57 pm" src="https://cloud.githubusercontent.com/assets/124493/22525346/d2d88230-e894-11e6-953e-5a39aa2f9e0b.png">

Maybe something like this?

<img width="320" alt="screen shot 2017-02-01 at 3 42 47 pm" src="https://cloud.githubusercontent.com/assets/124493/22525443/2cb13a9a-e895-11e6-8180-e6a3c94cae1b.png">
<img width="320" alt="screen shot 2017-02-01 at 3 43 15 pm" src="https://cloud.githubusercontent.com/assets/124493/22525449/2f2e8066-e895-11e6-863a-fb199baa3919.png">

**Comment by ryanpitts** [comment]
ooh, I'm a fan of the light border there. @kissane any thoughts?

**Comment by kissane** [comment]
> ooh, I'm a fan of the light border there. @kissane any thoughts?

Same, for sure.

**Comment by beep** [comment]
Added in 748b0a4a1215ba8b23ee13e9c1c47d284fd6f558!

(Let’s double check this fix when it merges? I had to make a minor structural tweak to `.profile` objects, which seems fine here, but holler if any regressions sneak in.)

**Comment by kissane** [comment]
Shall do!

**Comment by ryanpitts** [comment]
on staging now: https://opennews-source-staging.herokuapp.com/organizations/propublica/

**Comment by kissane** [comment]
Looks perfect to me.
