### ISSUE TITLE
cursor: pointer on active nav items?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#65]
@beep just wondering about this (I guess my screenshot doesn't capture, but right now it's the text selector when you hover the active nav item)

![screen shot 2017-02-01 at 11 45 13 am](https://cloud.githubusercontent.com/assets/56477/22523420/40b317a0-e874-11e6-9ec6-75b0824d11b4.png)

**Comment by beep** [comment]
Ah, that’s a dumb habit of mine: that should definitely signal that it’s actionable.

I’ll ditch that now.
