### ISSUE TITLE
Comment count

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#7]
Having some issues getting Disqus’ `count.js` (the comment count script) to work when loaded alongside `embed.js` (the embed comment script).

**Comment by beep** [comment]
This is in place now on [the article template](http://sourcedev.ethanmarcotte.com/article.php), but it’s…wonky. A few problems I’m running into:

- Disqus seems to cache old comment totals;
- Disqus formats the comment counts as `X comments`, and there’s no way to customize it; (e.g., “999’; “2.5K”)
- I haven’t found a reliable, non-buggy way to update the comment count when…new comments are added.

I’ve written a little extra code to hack around all of these problems, but Disqus is a bit of a black box, code-wise, which makes it hard.

I’m going to poke at it a bit more this week. I’ll keep this open for now!

**Comment by beep** [comment]
On https://opennews-source-staging.herokuapp.com/articles/what-youve-been-making-nov-9/

<img width="205" alt="screen shot 2017-01-25 at 8 22 29 pm" src="https://cloud.githubusercontent.com/assets/124493/22316612/5961013c-e33c-11e6-8a02-81ef956278d8.png">

okay yep I know what this is

**Comment by beep** [comment]
@ryanpitts could you add the following to the article template’s JS block?

```javascript
var disqus_config = function () {
    this.callbacks.onReady = [function( comment ) {
        $( document ).trigger( "comments-loaded" );
    } ];
    this.callbacks.onNewComment = [function( comment ) { 
        $( document ).trigger( "comments-new" );
    }];
};
```

I’m assuming there’s a `disqus_config` on the page already; the `this.callbacks.onReady` and `this.callbacks.onNewComment` handlers are what need to be added. So basically, this bit:

```javascript
    this.callbacks.onReady = [function( comment ) {
        $( document ).trigger( "comments-loaded" );
    } ];
    this.callbacks.onNewComment = [function( comment ) { 
        $( document ).trigger( "comments-new" );
    }];
```

Thank you!

**Comment by ryanpitts** [comment]
Yep, is this better served in the `head` or just before closing `body`?

**Comment by beep** [comment]
@ryanpitts Oh, six of one, really. I usually keep JS in the head, me, but I’d say put it wherever you’ve got the other disqus config variables.

**Comment by ryanpitts** [comment]
@beep Just pushed a new article_detail template with this update. Script in the head looks like this:

```
<script>
    var disqus_shortname = "source-opennews";
    var disqus_config = function () {
        this.page.url = '//{{ request.get_host() }}{{ article.get_absolute_url() }}';
        this.page.identifier = 'article_detail_{{ article.pk }}';
        this.page.title = '{{ article.title }} - Source';
        
        this.callbacks.onReady = [function( comment ) {
            $( document ).trigger( "comments-loaded" );
        } ];
        this.callbacks.onNewComment = [function( comment ) { 
            $( document ).trigger( "comments-new" );
        }];
    };
    
    (function() {
        var d = document, s = d.createElement('script');
        
        s.src = '//'+ disqus_shortname + '.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
```

Not sure it's fixed the N/A problem though. [Here's an example](https://opennews-source-staging.herokuapp.com/articles/introducing-agate/) to check out; it's got 36 comments loading fine in the thread now.

**Comment by beep** [comment]
> Script in the head looks like this:

Woo! Thanks, @ryanpitts.

> Not sure it's fixed the N/A problem though. Here's an example to check out; it's got 36 comments loading fine in the thread now.

Oh, okay! Thanks, @ryanpitts—I’ll take a look this morning.

One quick aside:

```
    (function() {
        var d = document, s = d.createElement('script');
        
        s.src = '//'+ disqus_shortname + '.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();```

I’m currently loading Disqus’ `embed.js` as part of `js/comments-disqus.js`. (I totally should’ve pointed that out—sorry!) If we’re double-loading `embed.js`, that _could_ be related. (I’m seeing a `Use DISQUS.reset instead of reloading embed.js please` error in the console.)

What’s your preference?

- Keep all Disqus-related loading scripts in the `head`, or
- Slim down the `head` to `disqus_shortname` and `disqus_config`, and leave the loading stuff in `main.js`?

**Comment by ryanpitts** [comment]
@beep ah, I'd totally love to get that out of the `head`. It looks like that whole function can be removed?

Also should we swap `disqus_id` in `config.js` to "source-opennews"?

**Comment by beep** [comment]
@ryanpitts Yep! Or I can switch all the internal references to point to the `disqus_shortname` you’ve got in the `head`. Either way.

**Comment by ryanpitts** [comment]
@beep I do like the idea of keeping all those things in `config.js`, that seems wise.

For now I manually edited the `initial.js` in `dist` for now and was able to streamline out all the extraneous stuff on the article page. No more double-loading `embed.js` here: https://opennews-source-staging.herokuapp.com/articles/introducing-agate/

**Comment by beep** [comment]
@ryanpitts Awesome. Still seeing the `N/A` here—I assume you are, too—so I’ll dig into that now.

**Comment by ryanpitts** [comment]
skrr skrr https://opennews-source-staging.herokuapp.com/articles/introducing-agate/
