### ISSUE TITLE
FINAL TEMPLATE CHECKLIST

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#71]
**Homepage** https://github.com/OpenNews/opennews-source/issues/57
[example](https://opennews-source-staging.herokuapp.com/)
* [x] beep
* [x] kissane

***

**Article detail** https://github.com/OpenNews/opennews-source/issues/22
[example 1](https://opennews-source-staging.herokuapp.com/articles/how-npr-transcribes-and-fact-checks-debates-live/) [example 2](https://opennews-source-staging.herokuapp.com/articles/pluggable-data/)
* [x] beep
* [x] kissane

***

**Article list** https://github.com/OpenNews/opennews-source/issues/70
[example](https://opennews-source-staging.herokuapp.com/articles/)
* [x] beep
* [x] kissane

***

**Article list by tag** https://github.com/OpenNews/opennews-source/issues/70
[example](https://opennews-source-staging.herokuapp.com/articles/tags/design/)
* [x] beep
* [x] kissane

***

**Search results** https://github.com/OpenNews/opennews-source/issues/86
[example](https://opennews-source-staging.herokuapp.com/search/?q=propublica)
* [ ] beep
* [ ] kissane

***

**Community landing page** https://github.com/OpenNews/opennews-source/issues/50
[example](https://opennews-source-staging.herokuapp.com/community/)
* [x] beep
* [x] kissane

***

**Person list** https://github.com/OpenNews/opennews-source/issues/45
[example](https://opennews-source-staging.herokuapp.com/people/)
* [x] beep
* [x] kissane

***

**Person detail** https://github.com/OpenNews/opennews-source/issues/37
[example 1](https://opennews-source-staging.herokuapp.com/people/tiff-fehr/) [example 2](https://opennews-source-staging.herokuapp.com/people/jeremy-bowers/)
* [x] beep
* [x] kissane

***

**Organization list** https://github.com/OpenNews/opennews-source/issues/49
[example](https://opennews-source-staging.herokuapp.com/organizations/)
* [x] beep
* [x] kissane

***

**Organization detail** https://github.com/OpenNews/opennews-source/issues/62
[example](https://opennews-source-staging.herokuapp.com/organizations/propublica/)
* [x] beep
* [x] kissane

***

**Code list** 
[example](https://opennews-source-staging.herokuapp.com/code/)
* [ ] beep
* [ ] kissane

***

**Code list by tag** 
[example](https://opennews-source-staging.herokuapp.com/code/tags/python/)
* [ ] beep
* [ ] kissane

***

**Code detail** https://github.com/OpenNews/opennews-source/issues/36
[example 1](https://opennews-source-staging.herokuapp.com/code/agate/) [example 2](https://opennews-source-staging.herokuapp.com/code/narrative-charts/)
* [x] beep
* [x] kissane

***

**Jobs list**
[example](https://opennews-source-staging.herokuapp.com/jobs/)
* [ ] beep
* [ ] kissane

***

**Guide list**
[example](https://opennews-source-staging.herokuapp.com/guides/)
* [x] beep
* [x] kissane

***

**Guide detail**
[example 1](https://opennews-source-staging.herokuapp.com/guides/news-apps-essentials/) [example 2](https://opennews-source-staging.herokuapp.com/guides/defending-accounts/)
* [x] beep
* [x] kissane

***

**Submit Code form** https://github.com/OpenNews/opennews-source/issues/43
[example](https://opennews-source-staging.herokuapp.com/code/suggest/)
* [x] beep
* [x] kissane

***

**Submit Guide form**
[example](https://opennews-source-staging.herokuapp.com/guides/suggest/)
* [ ] beep
* [ ] kissane

***

**Submit Article form** https://github.com/OpenNews/opennews-source/issues/87
[example](https://opennews-source-staging.herokuapp.com/articles/suggest/)
* [ ] beep
* [ ] kissane

***

anything else?

**Comment by ryanpitts** [comment]
@beep @kissane does it feel useful to make a tracking issue like this so we can see which templates are "done"?

**Comment by beep** [comment]
@ryanpitts This is _tremendously_ helpful, thank you! I’ll start working through this in the morning.

**Comment by ryanpitts** [comment]
@beep awesome, I'll fill out the rest of the list tonight.

**Comment by ryanpitts** [comment]
OK, I think this list captures everything.

**Comment by kissane** [comment]
This is incredible, thank you @ryanpitts

**Comment by kissane** [comment]
@ryanpitts Shall I start closing things that are double-checked above?

**Comment by beep** [comment]
I think I have checked off everything that’s implemented!

(@ryanpitts, you are _uhmazing._)

**Comment by ryanpitts** [comment]
@kissane sure!

**Comment by ryanpitts** [comment]
@beep @kissane I just updated the "Code list" and "Code list by tag" entries in the checklist. One thing re: "Code list by tag" -- it seems like we might need some affordance for backing back _up_ a level once someone has drilled down. Like if you click on the "python" tag and get this, what do you do to back up to the main "Code" page? (This situation will also pop up in article tag lists)

![screen shot 2017-02-02 at 3 26 16 pm](https://cloud.githubusercontent.com/assets/56477/22573089/1ba9b4b2-e95c-11e6-8117-dca299d9420c.png)

**Comment by kissane** [comment]
Would make the Code lead a link, it occurs to me. We'll probably find a few of these kinds of things this week that we need to sort out, but @beep says he'll reply to our emails if we get stuck. 🙏🏻

**Comment by beep** [comment]
_heck yes he will_

**Comment by ryanpitts** [comment]
probably just a style that keeps links inside `.page-title-lead` the same dark gray, then?

![screen shot 2017-02-02 at 3 36 45 pm](https://cloud.githubusercontent.com/assets/56477/22573531/45ebd2ee-e95e-11e6-8fad-e019c702aee1.png)

**Comment by kissane** [comment]
I like this

**Comment by ryanpitts** [comment]
OK, I don't think we have feedback threads for these, but these are ready for checkoff I believe:

* Guides list page: https://opennews-source-staging.herokuapp.com/guides/
* Guides detail page: https://opennews-source-staging.herokuapp.com/guides/defending-accounts/ & https://opennews-source-staging.herokuapp.com/guides/news-apps-essentials/

The guide_detail template is currently not doing anything with the cover image that shows up on the list page ... and I think I actually prefer that? Pulls you right into the articles, which likely have promo images of their own.

**Comment by kissane** [comment]
Guide list page is perfect, checked. 

Guides detail page is gorgeous and my only questions are whether we should stick the curator's bio down underneath the whole thing, and whether the 3rd party credits I see exist in the CMS are hooked up to display on the site. (I added some in the CMS, but of course that doesn't hit staging.)

**Comment by ryanpitts** [comment]
OK, pushed that fix, bio to the bottom of page. (Plus checked 3rd party credits): https://opennews-source-staging.herokuapp.com/guides/defending-accounts/

**Comment by kissane** [comment]
THX RYAN

**Comment by kissane** [comment]
can close anytime!

**Comment by ryanpitts** [comment]
awesome, I'll check you off on those two pages above!

**Comment by kissane** [comment]
They should be all checked! Maybe my checking didn't take

**Comment by ryanpitts** [comment]
@kissane new updates to check:
* Suggest a guide form: https://opennews-source-staging.herokuapp.com/guides/suggest/
* Jobs list: https://opennews-source-staging.herokuapp.com/jobs/
* Search results: https://opennews-source-staging.herokuapp.com/search/?q=propublica
* Suggest article: https://opennews-source-staging.herokuapp.com/articles/suggest/

OMG THAT'S ALL OF THEM

**Comment by ryanpitts** [comment]
there are a few unchecked things here. shall I leave this open, or move things to separate issues?

**Comment by ryanpitts** [comment]
ok to close this one @kissane ?

**Comment by kissane** [comment]
yis!
