### ISSUE TITLE
Articles, tables, and rows, oh my

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#73]
https://opennews-source-staging.herokuapp.com/articles/same-diff-trump-noms/

@kissane, do you know how frequently tables are used on articles? Follow-up question, should I add some basic table styles? 😀 

/ping #22 #71

**Comment by kissane** [comment]
We do use tables fairly frequently, and I would call this a…priority 3, for you, today? If you have time lying around, then yes please, we would love that, but if Ryan needs help wrangling something big, we can always make up the tables styles ourselfs.

**Comment by beep** [comment]
@kissane That’s super helpful, thanks! I’ll note it as an enhancement for now.

**Comment by kissane** [comment]
Ah yes, that is what adults call things that are this. Thank you!

**Comment by beep** [comment]
Added in https://github.com/OpenNews/opennews-source/commit/b0d4ae769f78e0bd6b2670e7bd6fc97ac7ec8558!

![screen shot 2017-02-02 at 1 26 09 pm](https://cloud.githubusercontent.com/assets/124493/22562583/301c21fc-e94b-11e6-931d-93713d8e490c.png)

**Comment by kissane** [comment]
Beautiful! Thank you!
