### ISSUE TITLE
create new CMS logins

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#74]
I need to add admin records for @kissane @tsl-lindsay

**Comment by kissane** [comment]
clapping my hands like a happy victorian child

**Comment by ryanpitts** [comment]
what username pattern would you like for these logins? I think old source had `erinkissane` but I can sure do whatever pattern most fits the way you like to log into things

**Comment by kissane** [comment]
ekissane would be awesome for me, thank you!

**Comment by kissane** [comment]
Have verified mine, everything looks awesome.

**Comment by kissane** [comment]
No, fingers, no.

**Comment by ryanpitts** [comment]
these are all done, unless anyone would like logins set up on staging as well
