### ISSUE TITLE
Templates, round #2

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#8]
- [x] [Home](https://wireframe.cc/d21Vel) ([notes](https://github.com/OpenNews/project-issues/issues/611))
- [x] [Person Profile](https://wireframe.cc/rUtpC1)
- [x] [Add Repo](https://wireframe.cc/6mChAO)
- [x] [Featured Repo](https://wireframe.cc/b1Hubw)

Just opening up an issue for the next week’s work!

**Comment by beep** [comment]
@kissane: on [the featured repo wireframe](https://wireframe.cc/b1Hubw), what’s this bit for?

<img width="455" alt="screen shot 2017-01-19 at 10 26 38 am" src="https://cloud.githubusercontent.com/assets/124493/22112664/c96c110c-de31-11e6-8caa-cc777ecec0df.png">

**Comment by beep** [comment]
(Also, and this is a tiny tiny thing, but I can’t seem to copy/select text on the wireframes. Is there a setting I could flip to change that?)

**Comment by kissane** [comment]
@beep Oh right, sorry I failed to tell you about that mystery block— it's an embedded repo, as seen here: https://source.opennews.org/en-US/code/elex/

@ryanpitts knows the details on how that works, but I have forgotten them, alas. 

On the wireframe question, I'm afraid there's an extra step in the eejit app I used to make them—if you double-click on a text block, it should pop up a contextual menu like this:

<img width="653" alt="screen shot 2017-01-19 at 12 34 38 pm" src="https://cloud.githubusercontent.com/assets/1910034/22117905/b995859e-de43-11e6-9a61-ca46edfebf23.png">

And clicking the pencil icon should allow you to edit or copy the text. I am sorry it is not smarter. :/

**Comment by beep** [comment]
> @beep Oh right, sorry I failed to tell you about that mystery block— it's an embedded repo, as seen here: https://source.opennews.org/en-US/code/elex/

Oh, that’s massively helpful—thank you, @kissane.

@ryanpitts, is that an open source library I could look at, or one of your own devisin’?

> And clicking the pencil icon should allow you to edit or copy the text. I am sorry it is not smarter. :/

oh jeez i am such a maroon

Thank you, Erin!

**Comment by ryanpitts** [comment]
@beep yep, it's an open-source library called repo.js: https://github.com/darcyclarke/Repo.js. Super easy to drop in, e.g.:

    $('body').repo({ user: 'jquery', name: 'jquery', branch: 'master' });

I have to use a little bit of logic in our template, because not everything is on GitHub and we don't assume the default branch is `master`. Like so (with a bit of Django template logic wrapping it):

```
{% block site_js_extra %}
{% if 'github.com/' in code.url %}{# load the in-page repo browser #}
<script src="{{ static('code/js/repo.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
    var tmpGithubValues = '{{ code.url }}'.split('github.com/')[1].split('/');
    var sourceData = {
        githubUser: tmpGithubValues[0],
        githubRepo: tmpGithubValues[1],
        githubMasterBranch: '{{ code.repo_master_branch }}'
    };
    loadRepo(
        sourceData['githubUser'], sourceData['githubRepo'], sourceData['githubMasterBranch']
    );
});

function loadRepo(user, repo, branch) {
    var repoContainer = '<div class="code-repo-browse"><h5>Browse this repo</h5><div id="repo"></div></div>';
    $('#code-link-lists').addClass('code-repo-meta').before(repoContainer);
    $('#repo').repo({
        user: user,
        name: repo,
        branch: branch
    });
}
</script>
{% endif %}
{% endblock %}
```

**Comment by beep** [comment]
@ryanpitts: awesome, thanks! I’ll see about working this in :)

**Comment by beep** [comment]
@kissane I don’t seem to have access to the `notes` for [the homepage wireframe](https://github.com/OpenNews/project-issues/issues/611). Could you paste them in here?

(I should’ve noticed this earlier. Sorry!)

**Comment by beep** [comment]
Got a first pass of the homepage in for today’s delivery. If the notes require any revisions, I’ll tackle them in the coming week!

Moving onto browser/device QA now!
