### ISSUE TITLE
Learning article transition 

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#82]
@ryanpitts, as I audit the site data, should I be doing anything in particular to the articles formerly known as Learning to make sure they show up right in the new site? They had things like a TOC, it occurs to me. Erp. Maybe this is two things—what we do now before launch, with tags and things, and whether we later re-implement optional TOCs? Grrrrr I should have thought of this earlier.

**Comment by ryanpitts** [comment]
I was thinking based on wireframes (as well as nav not breaking out "learning" any more) that there wasn't going to be a different display based on story type -- argh, I apologize for not asking that explicitly.

I think we should make sure that things are displaying well pre-launch, and then have a conversation about section-specific treatments. If they're useful, we can still totally do them.

**Comment by kissane** [comment]
Yeah, I was literally only thinking about getting the articles integrated, and hadn't gone back to look at their special display type—this is entirely on me. I definitely don't want to try to deal with intra-article stuff right now!

Are there any tagging things I need to sort out, though, to normalize these for the new site, as far as you know? Looking at the ones we've migrated, I might add new tags now that we're not restricted to a single tag by the Learning section rules. (Example https://opennews-source-staging.herokuapp.com/learning/pushing-hot-buttons-censusgov/ )

**Comment by ryanpitts** [comment]
by all means, tag away! Won't affect anything.

The [article list](https://opennews-source-staging.herokuapp.com/articles/) will pick up all articles, regardless of what section they are assigned to. (Whereas the old Source had a Features list and a Learning list that excluded each other.) We can still capture "section" metadata in the admin though for future use of whatever kind.
