### ISSUE TITLE
Template integration: jobs_list

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#84]
OK, this one is 99% done and looking good, I think. @beep I hate to bug you about this, but I'm not sure why `.icon-email` is not working. Looks like the svg and png are in place and the css is there for it, but it's returning an empty image.

https://opennews-source-staging.herokuapp.com/jobs/

**Comment by beep** [comment]
> @beep I hate to bug you about this

No worries at _all_, @ryanpitts, I’m more than happy to help! Holler at me any time.

> I'm not sure why .icon-email is not working. Looks like the svg and png are in place and the css is there for it, but it's returning an empty image.

It’s returning an image, but annoyingly, it’s returning a _white_ image. (And I love that browsers [preview it on a ~white background](https://cl.ly/0p2C2x2J3T2N).) I just created an alternate “dark” email icon `email-alt.svg`, which you can use with the `icon-email-alt` class, and tossed it into #88 for your review.

**Comment by beep** [comment]
Just as a point of interest: if we think we’ll need light and dark versions of most of our icons, grunticon has an option that allows us to _embed_ icons directly in our pages, which lets us color them directly with CSS. (See the “Can I apply CSS to them?” section of (grunticon.com)[http://www.grunticon.com/].)

I think we’re good with the current approach right now, but we could look into that if we’ll need a fair bit of icon reuse across different kinds of backgrounds.

**Comment by ryanpitts** [comment]
> It’s returning an image, but annoyingly, it’s returning a white image.

OMG I can't believe I didn't consider that. Thank you!

> we could look into that if we’ll need a fair bit of icon reuse across different kinds of backgrounds.

I'm pretty sure that 95% of our use is going to be on the white background, but very good to know this is an option.

**Comment by beep** [comment]
> OMG I can't believe I didn't consider that. Thank you!

Of course! (And dude no lie i do this _at least_ five times over the course of any given week)

**Comment by ryanpitts** [comment]
@beep I have now `grunt grunticon`'d successfully. Oontz.

**Comment by ryanpitts** [comment]
@kissane this is ready for a final look I think. https://opennews-source-staging.herokuapp.com/jobs/

**Comment by kissane** [comment]
Looks awesome, forgot to say that
