### ISSUE TITLE
Template integration: search results!

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#86]
OMG! These are so pretty! For example:

* https://opennews-source-staging.herokuapp.com/search/?q=propublica
* https://opennews-source-staging.herokuapp.com/search/?q=django

I'm inline styling the light border around the search box for now, until I am daring enough to update some scss.

**Comment by ryanpitts** [comment]
Just pushed some significant improvements to search result ordering on these pages, e.g. https://opennews-source-staging.herokuapp.com/search/?q=propublica

**Comment by kissane** [comment]
👍👍👍
