### ISSUE TITLE
/about/ page?

### ISSUE THREAD

**Issue by ryanpitts** [OpenNews/opennews-source#89]
Just pushed the v2 version of the template we use for pages like https://opennews-source-staging.herokuapp.com/about/. @kissane, I'm not sure if we still plan to actually use these. Right now the "learn more about this project"-type links are pointing to opennews.org, but they can certainly be pointed to a page like this if we like.

**Comment by kissane** [comment]
I would love to have a flat page for this, and can add the fresh new copy to it whenever it's convenient!

**Comment by ryanpitts** [comment]
Awesome, just edit the `about` page here and let me know when it's safe to link up: https://opennews-source-staging.herokuapp.com/admin/flatpages/flatpage/

I think we probably don't need the `contribute` and `subscribe` pages anymore, right? The `contribute` would be replaced by the "suggest an article" form, and the `subscribe` by the email newsletter link? If not, lmk.

**Comment by kissane** [comment]
I *think* this page is now correct, but I can't preview it to be sure—when I hit "view on site" it redirects to the Articles page, which I assume is something to do with it not being live or…something? Maybe @ryanpitts knows the solution to the mystery.

**Comment by ryanpitts** [comment]
hahaha, this was an overaggressive fix for redirecting the `/learning/` page, will update

**Comment by kissane** [comment]
Respect to that fix, it is srs.

**Comment by ryanpitts** [comment]
ok this works now: https://opennews-source-staging.herokuapp.com/about/

Looks like this should be wired up in the footer link, and in the homepage blurb. @kissane anywhere else?

**Comment by kissane** [comment]
@ryanpitts Perfect, thanks, and those are indeed the spots!

**Comment by ryanpitts** [comment]
@kissane one more question while I'm updating those links. Current the "contribute your work" links in the footer and the homepage blurb point to `mailto:source@opennews.org`.

Have you had a chance to look at & test the [article submit form](https://opennews-source-staging.herokuapp.com/articles/suggest/) yet? Do you want me to change the "contribute" links to point to that form?

**Comment by kissane** [comment]
@ryanpitts I like the form though I haven't tested it yet, but I *think* we should point to the Contribute flat page, which I will update to point to the article and repo submission forms. It needs updating, but you could do the pointering now and I will make sure I do the editing.

**Comment by ryanpitts** [comment]
No problem, will point those at `/contribute/`

**Comment by ryanpitts** [comment]
actually, I shouldn't close this if you still have text updates for either of those pages

**Comment by kissane** [comment]
Both pages are all set, closing it up!
