### ISSUE TITLE
Add repo.js to featured repo template

### ISSUE THREAD

**Issue by beep** [OpenNews/opennews-source#9]
Per https://github.com/OpenNews/opennews-source/issues/8#issuecomment-273847836

**Comment by beep** [comment]
@ryanpitts, quick question for you:

```
    var sourceData = {
        githubUser: tmpGithubValues[0],
        githubRepo: tmpGithubValues[1],
        githubMasterBranch: '{{ code.repo_master_branch }}'
    };
    loadRepo(
        sourceData['githubUser'], sourceData['githubRepo'], sourceData['githubMasterBranch']
    );
```

Is the branch value stored separately from the repo link? e.g., if Elex’s default branch was `https://github.com/newsdev/elex/tree/trends-tests` instead of `master`, would the code repo link be `https://github.com/newsdev/elex`, but the branch name is passed directly to the JS?

(I was just writing a little repo function based on https://github.com/OpenNews/opennews-source/issues/8#issuecomment-273847836, and thought I could get all the required information from the link on the page, but _then_ I thought I should check with you before making any more assumptions. :D)

**Comment by ryanpitts** [comment]
Yep, the database model includes a `repo_master_branch` field, which we added after running into an edge case where a project's primary branch was `gh-pages`.

If you pass in an empty `branch` param to repo.js, it just assumes `master` and moves on with life. That field in the admin just gives us a way to override on the rare cases where it's necessary. I think we have like 4-5 records like that.

**Comment by beep** [comment]
@ryanpitts That’s super helpful, thank you!

So here’s a block of code I wrote:

```javascript
        var $repo_link = $( ".link-code-repo" );

        var parseRepoLink = function( link ) {
            var sourceData = false,
                githubValues = link.split( "github.com/" )[ 1 ].split( "/" ),
                branchCheck = link.split( "tree/" )[ 1 ];

            if ( githubValues.length === 2 ) {
                var user = githubValues[ 0 ],
                    repo = githubValues[ 1 ],
                    branchName = ( branchCheck ) ? branchCheck : "master";

                sourceData = {
                    githubUser: user,
                    githubRepo: repo,
                    githubMasterBranch: branchName
                };

                return sourceData;
            }
        };

        if ( $repo_link.length ) {

            var data = parseRepoLink( $repo_link.attr( "href" ) );

            if ( data ) {
                var $container = $repo_link.parents( "div" );

                $container.append( '<div class="browse-repo"><h2 class="hed-label">Browse Repo</h2></div>' )

                $( ".browse-repo" ).repo( {
                    user: data.githubUser,
                    name: data.githubRepo,
                    branch: data.githubMasterBranch
                } );
            }
        }
```

In short, it does the following:

1. Looks for an `a.link-code-repo` on the page, and grabs the `href`.
2. If the link is found, it breaks it up into the requisite parts: username, repo, and branch.
  1. If `tree/[branch]` isn’t present in the link, the branch value defaults to `master`.
3. The repo script is invoked with those three pieces of data.

In other words, all your templates would need to do is _link_ to the repo in the page, and the script would take over from there.

That said, that’s just the rabbit hole I ran down this morning. What’s the easiest/best approach for _you_?

1. Would you rather include the branch name as a separate JS variable in the `head`, or
2. link to the branch in the body of the page?

**Comment by ryanpitts** [comment]
Yep, that seems fine to me. The values we store are:

* `url`: e.g. "https://github.com/OpenNews/opennews-source" or "https://github.com/MinnPost/simple-map-d3"
* `repo_master_branch`: e.g. "master" or "2.0"

So we aren't specifically _storing_ a `tree/[branch]` version of any URLs, we've just been linking to the main repo page and letting GitHub sort that for viewers.

That said, it feels like the above approach keeps the on-page stuff on Source nice and simple. It would not be hard for me to build the link in the body of the page like:

```
{% if code.repo_master_branch and code.repo_master_branch != 'master' %}
    <a class="link-code-repo">{{ code.url }}/tree/{{ code.repo_master_branch }}</a>
{% else %}
    <a class="link-code-repo">{{ code.url }}</a>
{% endif %}
```

(I can tighten that up to one line in the actual template, but leaving it more readable here.)

Unless I'm missing something dumb, I'm on board with this, and moving forward with the js you're suggesting here.

**Comment by beep** [comment]
> Unless I'm missing something dumb, I'm on board with this, and moving forward with the js you're suggesting here.

If you’re game, I think that sounds like a downright grand approach, Ryan.

**Comment by beep** [comment]
This is done and lookin’ _great_.
