### ISSUE TITLE
Launch plan: Redirects

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#90]
We needs 'em, for all the old URL patterns. :/

**Comment by ryanpitts** [comment]
do you mean for the old `/en-US/` URLs?

**Comment by kissane** [comment]
Yep—also I note that we're preserving the /learning/ URL pattern, which is maybe weird?

**Comment by ryanpitts** [comment]
Cool, support for old links is already taken care of. The `/en-US/` bits of a URL get stripped, and people are forwarded to the right article.

Support for `/learning/` is still in place, although _all_ articles show up in the articles list, regardless of section. Wasn't sure whether you and @tsl-lindsay wanted to continue using sections in any way, but I can rip that out as well if you like.

**Comment by kissane** [comment]
> Support for /learning/ is still in place, although all articles show up in the articles list, regardless of section. Wasn't sure whether you and @tsl-lindsay wanted to continue using sections in any way, but I can rip that out as well if you like.

We just chatted about this and would like to blow it up and just use /articles/ if that won't be too much of a PITA for you.

**Comment by ryanpitts** [comment]
no problem, will push to staging a fix that redirects all page requests to an `/articles/` version of the URL.

**Comment by kissane** [comment]
Thank you so much for having all of this thought through and under control. It's very soothing!

**Comment by ryanpitts** [comment]
ok, `/learning/` URLs should auto-forward now too:

* https://opennews-source-staging.herokuapp.com/learning
* https://opennews-source-staging.herokuapp.com/learning/if-it-needs-sign-its-probably-bad-design/

Also here's an example of the `/en-US/` redirects:

* https://opennews-source-staging.herokuapp.com/en-US/articles/if-it-needs-sign-its-probably-bad-design/

Any other redirects we need up?

**Comment by kissane** [comment]
Nope, looks perfect to me. Thx!
