### ISSUE TITLE
Bio field population for articles

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#94]
On article pages, is it possible to pull in Twitter bios to populate the bio area at the bottom if the real "Bio" field is blank on a Person record? Is that a huge pain?

**Comment by ryanpitts** [comment]
We can, it's not a pain at all. (We also store references to people's Twitter avatars btw.) My concern is over any Twitter TOS stuff this might run afoul of. I _think_ we might be OK using those as fallbacks, but @kissane how do you [read stuff like this](https://dev.twitter.com/overview/terms/display-requirements)?

**Comment by kissane** [comment]
Hmmmmmmm.

I don't think it's super clear. Safest thing would be to not do it BUT my inclination is to plonk in the bios and photos for now as fallbacks and then continue on our effort to replace them. Do you have gut feelings?

**Comment by ryanpitts** [comment]
same gut as you about the safest thing, but also agree on the lack of clarity. Let's try the fallback method

**Comment by kissane** [comment]
Awesome. Is it tempting fate to use those photos on the People list page?

**Comment by ryanpitts** [comment]
seems like a lot of people use the same avatar pic in a lot of places, so ...

**Comment by ryanpitts** [comment]
Hmm, so what we are storing is a reference to avatar images like so: https://pbs.twimg.com/profile_images/819655398923898881/WqEggJd0_normal.jpg

probably not OK for us to call those in directly

**Comment by kissane** [comment]
Yeeeeah nope. Ah, well, it was a nice thought.

**Comment by ryanpitts** [comment]
OK, article pages will now fall back to an author's twitter bio if no Source bio exists. (Same behavior as on the person pages)

**Comment by kissane** [comment]
Thank you!

**Comment by kissane** [comment]
Fix confirmed, closing
