### ISSUE TITLE
Updated images not appearing on Community landing

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#95]
On https://opennews-source-staging.herokuapp.com/community/, I'm seeing broken or placeholder images for Julia and the three featured orgs, all of which have updated photos/logos. Could be a caching thing?

**Comment by ryanpitts** [comment]
Ah, yeah that's almost certainly cache-related. The community page is brand new, so there's no built-in cache-busting when you save something related to it. I just filed a ticket for adding that https://github.com/OpenNews/opennews-source/issues/97

> Note: because this page pulls 3 random people and 3 random orgs, busting the cache will likely have the effect of rotating the current items off the page anyway.

**Comment by kissane** [comment]
Yay, thanks! Adding a cache-buster is way low on the priority list, I just wanted to make sure that was it.
