### ISSUE TITLE
How to feature people and orgs

### ISSUE THREAD

**Issue by kissane** [OpenNews/opennews-source#96]
My apologies if this is answered elsewhere, but how are we meant to select featured people and organizations? I poked around the obvious places for checkboxes but failed to find them.

**Comment by ryanpitts** [comment]
People and orgs don't have checkboxes -- they _could_ if you want, but I was working from [the wireframe](https://wireframe.cc/41mKHM) note:

> People and Org thumbnails get pulled from pool of perhaps 20 most recent orgs/people who wrote a Source post or were credited in a repo

Right now the [community page](https://opennews-source-staging.herokuapp.com/community/) is collecting the 20 most recent articles and the 20 most recent code libraries added to Source, and then displaying a random group of 3 people and 3 orgs from that pool.

If this still seems like a fine way to populate that page, that would be one less thing to manage manually.

**Comment by kissane** [comment]
> If this still seems like a fine way to populate that page, that would be one less thing to manage manually.

That is a wonderful way, and thanks for breaking down the specs for me!
